### ISSUE TITLE
微信APP支付，获取回调信息并进行验签的方法有吗？

### ISSUE THREAD

**Issue by MaQuanXin** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#1]

**Comment by fudiwei** [comment]
“App 支付的回调信息”你指的是什么？

是 App 支付以后微信推送给你下单时指定的 `notify_url` 地址上的信息吗？

[文档](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/main/docs/WechatTenpayV3/Advanced_ResponseSignatureVerification.md)中有写，可以看下。

**Comment by MaQuanXin** [comment]
> “App 支付的回调信息”你指的是什么？
> 
> 是 App 支付以后微信推送给你下单时指定的 `notify_url` 地址上的信息吗？
> 
> [文档](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/main/docs/WechatTenpayV3/Advanced_ResponseSignatureVerification.md)中有写，可以看下。

就是支付回调后的处理方法有整体的封装吗？下单时指定的 notify_url 这个访问的方法（APP支付的回调方法）

**Comment by fudiwei** [comment]
回调验签的话看这个文档：https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/main/docs/WechatTenpayV3/Advanced_ResponseSignatureVerification.md

回调解密的话看这个文档：https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/main/docs/WechatTenpayV3/Advanced_EventDataDecryption.md

还是说你希望有一个像对请求响应数据一样、可以对微信回调数据直接验签的方法？

**Comment by MaQuanXin** [comment]
> 回调验签的话看这个文档：https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/main/docs/WechatTenpayV3/Advanced_ResponseSignatureVerification.md
> 
> 回调解密的话看这个文档：https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/main/docs/WechatTenpayV3/Advanced_EventDataDecryption.md
> 
> 还是说你希望有一个像对请求响应数据一样、可以对微信回调数据直接验签的方法？

对，希望有一个封装好的方法（里边有获取微信回调回来的数据，进行验签，解密），然后比如方法值返回bool，表示是否可以继续处理订单状态就可以了。这样又减少了使用者的代码量

**Comment by fudiwei** [comment]
明白你的意思了。

现在已经提供解密数据的方法了；暂时还没提供对回调验签的方法、只有对响应验签的方法，像对回调验签的话需要你手动拼接一下待验签数据，然后利用库中提供的 `RSAUtility` 工具类验签。

这周我找时间再发一个版本，补上这个功能。

如果你有兴趣补全它，也欢迎 PR~

**Comment by MaQuanXin** [comment]
> 明白你的意思了。
> 
> 
> 
> 现在已经提供解密数据的方法了；暂时还没提供对回调验签的方法、只有对响应验签的方法，像对回调验签的话需要你手动拼接一下待验签数据，然后利用库中提供的 `RSAUtility` 工具类验签。
> 
> 
> 
> 这周我找时间再发一个版本，补上这个功能。
> 
> 
> 
> 如果你有兴趣补全它，也欢迎 PR~

好的，谢谢

**Comment by fudiwei** [comment]
升级至 v1.3.0。

具体用法请阅读下图中红圈的四个文档：

![image](https://user-images.githubusercontent.com/18504146/126281165-95e39f96-fb8c-43fc-bd50-870cfcafc313.png)

**Comment by fudiwei** [comment]
@MaQuanXin 没有其他问题我先关闭 Issue 了

**Comment by MaQuanXin** [comment]
> @MaQuanXin 没有其他问题我先关闭 Issue 了

![image](https://user-images.githubusercontent.com/46858390/126308271-97dd8643-c7bb-4f4e-877a-bdb4afd346a9.png)
出现了这个错误，我还没找到原因。这个的示例：https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/main/docs/WechatTenpayV3/Advanced_EventDataSignatureVerification.md

**Comment by fudiwei** [comment]
抱歉，之前的代码打包的有点儿问题，请升级至 v1.3.1。



***@***.***
 
发件人： 马全鑫
发送时间： 2021-07-20 18:23
收件人： fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat
抄送： RHQYZ; State change
主题： Re: [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat] 微信APP支付，获取回调信息并进行验签的方法有吗？ (#1)
@MaQuanXin 没有其他问题我先关闭 Issue 了

出现了这个错误，我还没找到原因。这个的示例：https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/main/docs/WechatTenpayV3/Advanced_EventDataSignatureVerification.md

**Comment by MaQuanXin** [comment]
> @MaQuanXin 抱歉，之前的代码打包的有点儿问题，请升级至 v1.3.1。

好的，已解决，谢谢
