### ISSUE TITLE
关于微信小程序平台签名问题

### ISSUE THREAD

**Issue by lxysjl** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#102]
请简要描述你所遇到的问题。
请问
https://developers.weixin.qq.com/miniprogram/dev/OpenApiDoc/getting_started/api_signature.html
SignWithSHA256(string privateKey, string message) 这个支持上面接口的RSA签名吗

public static string SignWithSM3(string privateKey, string message, bool asn1Encoding = true)
这个支持 上面接口SM2withSM3签名吗

**Comment by fudiwei** [comment]
你是指 TenpayV3 模块里的 RSAUtility、SM2Utility 是否可以用在这里？

这些算法都是国际标准，理论上都是一样的。
