### ISSUE TITLE
在接受微信通知的例子里面能加入被动回复的例子吗

### ISSUE THREAD

**Issue by KahrLu** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#103]
> **⚠⚠ 请注意：不符合格式要求的 Issue 可能会被直接关闭。**

---

**关于建议的简单描述**

可以在接受微信通知的例子里面能加入被动回复的例子吗？谢谢

---

**实现思路或解决方案**

---

**补充说明**

**Comment by fudiwei** [comment]
请参考此文档：

> https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/main/docs/WechatApi/Basic_EventDeserialization.md#%E8%A2%AB%E5%8A%A8%E5%9B%9E%E5%A4%8D

如果你是在写 Controller 的话，把文档示例里的 `replyXml` 作为 Action 的返回值就行了。
