### ISSUE TITLE
client.VerifyEventSignature  签名失败问题

### ISSUE THREAD

**Issue by vanteking** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#104]
bool valid = client.VerifyEventSignature(callbackTimestamp,
                callbackNonce,
                callbackModel.ToJson(),
                callbackSignature,
                callbackSerialNumber,out Exception error);
抛出的异常代码：确认过证书用的是apiclient_key.pem里面的内容
error:SKIT.FlurlHttpClient.Wechat.TenpayV3.Exceptions.WechatTenpayEventVerificationException: Verify signature of event failed. Please see the inner exception for more details. ---> System.Exception: There is no platform certificate matched the serial number: "3ACF2C7B883AC1CACB9DEE7E2F3C974A30DFC2D5". Please make sure you have downloaded platform certificates first.

**Comment by fudiwei** [comment]
https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/main/docs/WechatTenpayV3/Basic_EventSignatureVerification.md#%E9%87%8D%E8%A6%81%E9%A1%BB%E7%9F%A5

![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/18504146/94ab7344-58ba-4325-b5f4-676d2a704f11)
