### ISSUE TITLE
虚拟支付，道具发货推送事件，没见解密内容方法 是不是没有啊

### ISSUE THREAD

**Issue by lkd3063601** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#105]
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/15059204/e2666c55-1ef6-44a6-9d46-0c521005d9ec)
整个项目搜索xpay_goods_deliver_notify都没搜到相关的

**Comment by fudiwei** [comment]
[v2.31.0](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.Api/2.31.0) 已补充。

**Comment by lkd3063601** [comment]
好的谢谢，我是自己写了个类XPayGoodsDeliverNotifyEvent 继承的WechatApiEvent，我现在升级下，使用你最新的测试下，没问题的话 我在这里反馈下

**Comment by lkd3063601** [comment]
测试了下 完全没问题，赞一个
