### ISSUE TITLE
支付成功后返回的数据里 event_type 一直是空的是什么原因造成的？

### ISSUE THREAD

**Issue by vanteking** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#106]
微信小程序支付成功后的回调地址里接受的数据：
{"id":"fc682946-c392-534a-b180-2c0d5c3e6197","event_type":null,"summary":"支付成功","resource_type":null,"resource":{"algorithm":"AEAD_AES_256_GCM","original_type":null,"associated_data":null,"nonce":"19aBjcFaeKsi","ciphertext":"0H5OT1Su4687qC4lYxifrhjMNqzFAw7dGPX0vGRoty3bM3BOzAMtbtcwt3YbAOcCEpGQYLBi9pgdIkND2vvAN88gg5sAfiJhmUj+vp+E4dCTph1fF+x68+vFJmVg/UveRMoLBQ9hCXjL8lJkkP1wV6eJG1TopFKZPIo6nKUu0aNn6LRPiIapQJe0Sightq6GuPFwMjVvSIqZIWKKxgIzum22Ph967760O5QTtAX2Y29kSlx1NCtrrOfroG/ROTLA70I+L/9JDj+CkEd+tqdr5fOE2dQkJVIf/BADR69+SjpdYOqSNDFVhu+ud6uqok3CSPUW87wJDXig0hvS9dvmfUzgDN0AcXQTY4AJAdfmA4D62NGSojV8VKM6d8O3dLpXMJnqX1YbY2cGs1wunUTHPOscsdEL9kMDmQ4Uokuf0k6E5qLWXi4HJZOAbywh/RQhbGxYu2IzmJBR+IGL2fLGSjgAVL7T2LIawnbw6AfN4FwhdD9bfbdIe63VovKz9dgQg8ebVIwlvaxEhAWB2IpycPwe49gi6RXp75PpHwemvZdtBZIfHJ3yk+7DMuLy0sQkdqSj7NXXVs3seQ=="},"create_time":"0001-01-01T00:00:00+00:00"}

event_type 一直是空的是什么原因造成的？

**Comment by fudiwei** [comment]
这是你收到的回调原始内容，还是反序列化后再序列化的？

**Comment by vanteking** [comment]
> 这是你收到的回调原始内容，还是反序列化后再序列化的？

这是我收到的回调原始内容

**Comment by fudiwei** [comment]
那跟 SDK 没有关系。带着日志，工作时间去找微信技术支持：

https://support.pay.weixin.qq.com/online-service?from=wechatpay
