### ISSUE TITLE
SKIT.FlurlHttpClient.Tools.CodeAnalyzer nuget不存在，编译不通过

### ISSUE THREAD

**Issue by xiaomazz** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#107]
![2ab28efc-3523-4f95-82a2-78ce33a907ab](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/52307384/39c7870e-627e-4035-8852-159d967cb2f6)

**Comment by fudiwei** [comment]
命令行进到项目根目录下，手动执行 `dotnet restore`，退出并重启 VS 即可。
