### ISSUE TITLE
.NET Framework 4.6.1 请求直接卡死

### ISSUE THREAD

**Issue by DreamlessRaw** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#109]
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/47837339/640673c9-ef9b-492d-9cbf-6405dbe4ba95)
在.NET Core 6 环境下是正常的，但是在.NET Framework 4.6.1 环境下执行方法时卡住不动，没有任何响应

**Comment by fudiwei** [comment]
一般是因为在主线程中使用 `Task.Result` 或 `Task.Wait()` 导致死锁。

> https://learn.microsoft.com/zh-cn/archive/blogs/jpsanders/asp-net-do-not-use-task-result-in-main-context
