### ISSUE TITLE
[BUG] 获取微信OpenId异常

### ISSUE THREAD

**Issue by itcsdnnet** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#110]
近期调用微信登录异常如下：
Call failed. Resource temporarily unavailable (api.weixin.qq.com:443): GET https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=aaa&secret=bbb

百度后说微信 http keep-alive 时长为 20s，若20s后使用原始连接会报以上错误，对应帖子连接：https://juejin.cn/post/6865277186438496269

但实际代码中不存在超过20s的连接，且之前请求一直正常，对应代码如下，请协助解决，谢谢

// 获取连接
var client = CreateWeChatOpenClient();

var request = new CgibinTokenRequest();
var response = await client.ExecuteCgibinTokenAsync(request);

if (!response.IsSuccessful())
{
    throw new ApiResultException(ApiResultCodes.ServerInnerException, $"获取微信Token失败");
}

var openRequest = new SnsJsCode2SessionRequest
{
    JsCode = code,
    AccessToken = response.AccessToken
};

await client.ExecuteSnsJsCode2SessionAsync(openRequest, contextAccessor.HttpContext.RequestAborted);

**Comment by fudiwei** [comment]
偶发性的还是稳定复现？
