### ISSUE TITLE
[BUG] 企业微信授权返回model里的user_limit 类型需要改为long

### ISSUE THREAD

**Issue by lovheot** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#112]
var req = new SKIT.FlurlHttpClient.Wechat.Work.Models.CgibinServiceGetPermanentCodeRequest();
 req.TempAuthCode = authCode;
 req.AccessToken = accessToken ;
 var rep = await _wechatWorkClient.ExecuteCgibinServiceGetPermanentCodeAsync(req);

错误信息    Newtonsoft.Json.JsonReaderException: JSON integer 4294967295 is too large or small for an Int32. Path 'edition_info.agent[0].user_limit', line 1, position 1598.

**Comment by fudiwei** [comment]
已修复。将随下一 release 版本发布，敬请留意。
