### ISSUE TITLE
企业微信小程序下单

### ISSUE THREAD

**Issue by ichichchch** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#113]
您好我想请问一下企业微信的小程序下单接口在哪里
就是我找了源码 SKIT.FlurHttpClient.Wechat.Works\Models\CgibinMiniAppPay和SKIT.FlurHttpClient.Wechat.Works\Models\CgibinMiniProgram都没有这个接口
我们那个业务就是想把小程序里微信支付改成企业微信支付 谢谢您 辛苦了

**Comment by fudiwei** [comment]
具体是指哪一个接口？可以贴一下微信官方的文档链接吗？

**Comment by corningcode** [comment]
小程序下单接口官方文档  https://developer.work.weixin.qq.com/document/path/97322

**Comment by ichichchch** [comment]
是的 就是这个 小程序下单接口官方文档 https://developer.work.weixin.qq.com/document/path/97322
