### ISSUE TITLE
企业微信会话消息初始化失败

### ISSUE THREAD

**Issue by klj218** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#114]
![图片](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/134674296/3c9ae151-0521-4a0d-9a30-6f91691848cd)

**Comment by klj218** [comment]
想问一下，这个初始化失败是什么原因引起的？

**Comment by klj218** [comment]
按照示例代码使用：
            var manager = new InMemoryEncryptionKeyManager();
			manager.AddEntry(new EncryptionKeyEntry(1, PRIVATE_KEY));
			var options = new WechatWorkFinanceClientOptions()
			{
				CorpId = "{CorpId },
				SecretKey = "{SecretKey }",
				EncryptionKeyManager = manager // 密钥管理器的具体用法将在本章节下文详细介绍
			};
			var client = new WechatWorkFinanceClient(options);

**Comment by fudiwei** [comment]
请先确认企业微信提供的那 4 个 DLL 是否已正确下载并放入指定路径下。

此外如果是 Windows 操作系统，请确认本机 VC++ 运行库是否已正确安装。不确定的话可以打开下方微软官方提供的下载链接重新下载安装：

> https://learn.microsoft.com/zh-CN/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

最后再确认本机运行环境和项目的目标框架是多少位的，企业微信提供的这几个 DLL 都是 64 位的，只支持 64 位的程序。

**Comment by klj218** [comment]
已解决
