### ISSUE TITLE
[FEATURE] 能不能把MessageReply的几个对象抽象出来？

### ISSUE THREAD

**Issue by iam993** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#115]
> **⚠⚠ 请注意：不符合格式要求的 Issue 可能会被直接关闭。**

---

**关于建议的简单描述**

string replyXml = client.SerializeEventToXml(replyModel, safety: false);

这里的replyModel没有基类，而业务逻辑的代码是不确定向微信返回什么内容的，也许是文字，也许是图片。所以导致了这段代码必须写在各个业务逻辑内，而业务逻辑返回string replyXml，看着很笨。

---

**实现思路或解决方案**

如果你已有实现思路或解决方案，请在此贴出。

---

**补充说明**

请在此填写任何其他可以帮助说明的信息。

**Comment by fudiwei** [comment]
`WechatApiEvent` 就是基类呀。

**Comment by iam993** [comment]
> `WechatApiEvent` 就是基类呀。

但是 SerializeEventToXml<T> 中 T 的约束不仅是WechatApiEvent ，导致他没法序列化单纯的 WechatApiEvent 对象

**Comment by fudiwei** [comment]
明白你的意思了，我想想看怎么处理更合适一些。

**Comment by fudiwei** [comment]
v3.x 已废弃 `IXmlSerializable`、`IJsonerializable` 接口，你现在可以直接传递作为基类的 `WechatApiEvent` 对象。
