### ISSUE TITLE
想进行微信仿真测试系统测试，请问该如何修改接入的URL? 

### ISSUE THREAD

**Issue by LinJing517** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#130]
请简要描述你所遇到的问题。
https://[pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=23_1&index=1](https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=23_1&index=1)

例如，付款码支付URL：https://api.mch.weixin.qq.com/pay/micropay

变更为：https://api.mch.weixin.qq.com/xdc/apiv2sandbox/pay/micropay。

**Comment by fudiwei** [comment]
构造 Client 时的 Options 有一个 `Endpoint` 参数可以修改。

**Comment by LinJing517** [comment]
沙盒测试里的密钥 也会自动获取吗？

**Comment by fudiwei** [comment]
> 沙盒测试里的密钥 也会自动获取吗？

啥密钥？

**Comment by LinJing517** [comment]
异常测试，怎么在Http Header 中添加异常头 Wechatpay-Negative-Test 呢？

**Comment by fudiwei** [comment]
> 异常测试，怎么在Http Header 中添加异常头 Wechatpay-Negative-Test 呢？

可在构造阶段通过 `builder.UseHtpClient()` 传入一个自定义的 HttpClient 对象，指定其 `DefaultRequestHeaders` 属性。

也可通过自定义请求拦截器实现。

**Comment by LinJing517** [comment]
好的，已解决，感谢！感谢！
