### ISSUE TITLE
请问如何回复公众平台发的消息

### ISSUE THREAD

**Issue by Leblanc2025** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#132]
例程中给省略了，请问如何回复消息？.NET 6.0

**Comment by fudiwei** [comment]
分为主动回复和被动回复两种方式，前提是你已经熟悉相关的概念。

---

主动回复调这个接口：
> https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Service_Center_messages.html#%E5%AE%A2%E6%9C%8D%E6%8E%A5%E5%8F%A3-%E5%8F%91%E6%B6%88%E6%81%AF

怎么在本 SDK 里找到这个接口请看文档：
> [《开发文档：快速找到需要调用的 API 模型类名 / 方法名？》](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/main/docs/WechatApi/Basic_ModelDefinition.md#%E5%A6%82%E4%BD%95%E5%BF%AB%E9%80%9F%E6%89%BE%E5%88%B0%E9%9C%80%E8%A6%81%E8%B0%83%E7%94%A8%E7%9A%84-api-%E6%A8%A1%E5%9E%8B%E7%B1%BB%E5%90%8D--%E6%96%B9%E6%B3%95%E5%90%8D)

---

被动回复需要在微信回调的接口中直接 return 内容：
> https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Passive_user_reply_message.html

你可以自己拼 XML/JSON，也可以利用本 SDK 提供的扩展方法：
> [《开发文档：解析回调通知事件 —— 被动回复》](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/main/docs/WechatApi/Basic_EventDeserialization.md#%E8%A2%AB%E5%8A%A8%E5%9B%9E%E5%A4%8D)

**Comment by Leblanc2025** [comment]
已收到，非常感谢！
