### ISSUE TITLE
[BUG] 企微获取部门成员详情接口的gender类型定义错误

### ISSUE THREAD

**Issue by dabai** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#135]
**关于问题的简单描述**
类型定义错误。
企微获取部门成员详情接口中，性别gender接口返回的是string，与CgibinUserListResponse.cs定义的int不一致，会导致System.Text.Json.Serialization在反序列化时异常。
REF： https://developer.work.weixin.qq.com/document/path/90201

---

**与问题相关的源代码**
SKIT.FlurlHttpClient.Wechat.Work\Models\CgibinUser\CgibinUserListResponse.cs
```csharp
/// <summary>
/// 获取或设置性别。
/// </summary>
[Newtonsoft.Json.JsonProperty("gender")]
[System.Text.Json.Serialization.JsonPropertyName("gender")]
public int Gender { get; set; }
```

---

**异常堆栈或异常原因**

The JSON value could not be converted to System.Int32. Path: $.userlist[0].gender | LineNumber: 0 | BytePositionInLine: XXXX.

---

**发生问题的运行环境**

请在此填写以下几项内容：

1. 操作系统：如：Windows 11
2. .NET 版本：.NET 6.0
3. 使用的模块及版本：SKIT.FlurlHttpClient.Wechat.Work 3.2.1

**Comment by fudiwei** [comment]
可以先指定 JSON 序列化器为 Newtonsoft.Json 规避此错误，System.Text.Json 对标准化要求比较高。后面我会修复此问题。

**Comment by fudiwei** [comment]
已修复。将随下一版本 release，敬请留意。
