### ISSUE TITLE
CgibinMessageSendRequest.Types.TemplateCardMessage内部类存在相同名称Action

### ISSUE THREAD

**Issue by flyjoe0309** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#137]
> **⚠⚠ 请注意：不符合格式要求的 Issue 可能会被直接关闭。**

---

**关于问题的简单描述**

CgibinMessageSendRequest.Types.TemplateCardMessage.Types.Action与CgibinMessageSendRequest.Types.TemplateCardMessage.Types.ActionMenu.Types.Action冲突

---

**与问题相关的源代码**

public class TemplateCardMessage
{
    public static class Types
    {
        public class Source
        {
            //
            // 摘要:
            //     获取或设置来源图片的 URL。
            [JsonProperty("icon_url")]
            [JsonPropertyName("icon_url")]
            public string IconUrl { get; set; } = string.Empty;

            //
            // 摘要:
            //     获取或设置来源图片的描述。
            [JsonProperty("desc")]
            [JsonPropertyName("desc")]
            public string? Description { get; set; }

            //
            // 摘要:
            //     获取或设置来源图片的描述颜色类型。
            [JsonProperty("desc_color")]
            [JsonPropertyName("desc_color")]
            public int? DescriptionColorType { get; set; }
        }

        public class MainTitle
        {
            //
            // 摘要:
            //     获取或设置标题。
            [JsonProperty("title")]
            [JsonPropertyName("title")]
            public string Title { get; set; } = string.Empty;

            //
            // 摘要:
            //     获取或设置描述。
            [JsonProperty("desc")]
            [JsonPropertyName("desc")]
            public string? Description { get; set; }
        }

        public class Image
        {
            //
            // 摘要:
            //     获取或设置图片 URL。
            [JsonProperty("url")]
            [JsonPropertyName("url")]
            public string Url { get; set; } = string.Empty;

            //
            // 摘要:
            //     获取或设置图片的宽高比。
            [JsonProperty("aspect_ratio")]
            [JsonPropertyName("aspect_ratio")]
            public decimal? AspectRatio { get; set; }
        }

        public class QuoteArea
        {
            //
            // 摘要:
            //     获取或设置类型。
            [JsonProperty("type")]
            [JsonPropertyName("type")]
            public int? Type { get; set; }

            //
            // 摘要:
            //     获取或设置跳转链接。
            [JsonProperty("url")]
            [JsonPropertyName("url")]
            public string? Url { get; set; }

            //
            // 摘要:
            //     获取或设置跳转小程序的 AppId。
            [JsonProperty("appid")]
            [JsonPropertyName("appid")]
            public string? MiniProgramAppId { get; set; }

            //
            // 摘要:
            //     获取或设置跳转小程序的路径。
            [JsonProperty("pagepath")]
            [JsonPropertyName("pagepath")]
            public string? MiniProgramPagePath { get; set; }

            //
            // 摘要:
            //     获取或设置引用文献样式的标题。
            [JsonProperty("title")]
            [JsonPropertyName("title")]
            public string? Title { get; set; }

            //
            // 摘要:
            //     获取或设置引用文献样式的引用文案。
            [JsonProperty("quote_text")]
            [JsonPropertyName("quote_text")]
            public string? QuoteText { get; set; }
        }

        public class EmphasisContent : MainTitle
        {
        }

        public class VerticalContent : MainTitle
        {
        }

        public class HorizontalContent
        {
            //
            // 摘要:
            //     获取或设置二级标题。
            [JsonProperty("keyname")]
            [JsonPropertyName("keyname")]
            public string Key { get; set; } = string.Empty;

            //
            // 摘要:
            //     获取或设置二级文本。
            [JsonProperty("value")]
            [JsonPropertyName("value")]
            public string Value { get; set; } = string.Empty;

            //
            // 摘要:
            //     获取或设置链接类型。
            [JsonProperty("type")]
            [JsonPropertyName("type")]
            public int? Type { get; set; }

            //
            // 摘要:
            //     获取或设置跳转链接。
            [JsonProperty("url")]
            [JsonPropertyName("url")]
            public string? Url { get; set; }

            //
            // 摘要:
            //     获取或设置附件的 MediaId。
            [JsonProperty("media_id")]
            [JsonPropertyName("media_id")]
            public string? MediaId { get; set; }

            //
            // 摘要:
            //     获取或设置成员账号。
            [JsonProperty("userid")]
            [JsonPropertyName("userid")]
            public string? UserId { get; set; }
        }

        public class Action
        {
            //
            // 摘要:
            //     获取或设置跳转链接类型。
            [JsonProperty("type")]
            [JsonPropertyName("type")]
            public int? Type { get; set; }

            //
            // 摘要:
            //     获取或设置跳转链接样式的文案内容。
            [JsonProperty("title")]
            [JsonPropertyName("title")]
            public string Title { get; set; } = string.Empty;

            //
            // 摘要:
            //     获取或设置跳转链接。
            [JsonProperty("url")]
            [JsonPropertyName("url")]
            public string? Url { get; set; }

            //
            // 摘要:
            //     获取或设置跳转小程序的 AppId。
            [JsonProperty("appid")]
            [JsonPropertyName("appid")]
            public string? MiniProgramAppId { get; set; }

            //
            // 摘要:
            //     获取或设置跳转小程序的路径。
            [JsonProperty("pagepath")]
            [JsonPropertyName("pagepath")]
            public string? MiniProgramPagePath { get; set; }
        }

        public class ActionMenu
        {
            public static class Types
            {
                public class Action
                {
                    //
                    // 摘要:
                    //     获取或设置操作按钮 Key。
                    [JsonProperty("key")]
                    [JsonPropertyName("key")]
                    public string Key { get; set; } = string.Empty;

                    //
                    // 摘要:
                    //     获取或设置操作按钮文案。
                    [JsonProperty("text")]
                    [JsonPropertyName("text")]
                    public string Text { get; set; } = string.Empty;

                }

注意，请不要以截图形式提供代码。
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/168146843/212daa7b-230d-4759-9814-01649d037226)
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/168146843/3774e34c-6241-4ac6-a1f2-6915cbb45732)

---

**异常堆栈或异常原因**

处理请求时发生未处理的异常。
InvalidOperationException：不能将 schemaId“$Action”用于类型“$SKIT”。FlurlHttpClient.Wechat.Work.Models.CgibinMessageSendRequest+Types+TemplateCardMessage+Types+ActionMenu+Types+Action“。相同的 schemaId 已用于类型“$SKIT。FlurlHttpClient.Wechat.Work.Models.CgibinMessageSendRequest+Types+TemplateCardMessage+Types+Action”

---

**发生问题的运行环境**

请在此填写以下几项内容：

1. 操作系统：Windows 10专业版64位
2. .NET 版本：.NET 8.0
3. 使用的模块及版本：SKIT.FlurlHttpClient.Wechat.Work
4. 其他环境信息。

---

**补充说明**

请在此填写任何其他可以定位问题的信息。

**Comment by fudiwei** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1607#issuecomment-607170559
