### ISSUE TITLE
请问怎么输出或者查看生成的签名？

### ISSUE THREAD

**Issue by Lingweiy** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#138]
调用微信的下单接口和获取证书接口都返回签名错误，想输出签名看看是什么问题

**Comment by fudiwei** [comment]
[《高级技巧：使用拦截器》](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/main/docs/WechatTenpayV3/Advanced_Interceptor.md)

P.S. 最简单的方式其实是用 Fiddler 或者 Charles 抓个包……

**Comment by Lingweiy** [comment]
好的，感谢大佬，我试试

**Comment by Lingweiy** [comment]
我调用查询证书方法ExecuteQueryCertificatesAsync返回错误的签名，
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/48813545/82e09d7b-905f-47f9-b549-1b8be29f55bb)
这是new httpclient的方法：
![1715135783441](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/48813545/e29b3600-4aef-411b-ba86-d488d93c6910)
这是调用的地方：
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/48813545/c9cd05a1-4d47-4047-a252-03211338d502)
请问是哪里写错了吗？

**Comment by Lingweiy** [comment]
我确定我的参数没问题，使用postman可以请求通，但使用sdk就返回签名错误

**Comment by fudiwei** [comment]
只能是 MerchantId、MerchantCertificateSerialNumber、MerchantCertficatePrivateKey 这三个参数有问题，比如混用了不同商户号的证书之类的。再仔细检查检查吧，代码里断点看看传进来的是啥。

实在找不出来你可以在微信商户后台重新申请一张新的证书。

**Comment by Lingweiy** [comment]
破案了，私钥文件弄错了！不知道咋回事没覆盖了，感谢大佬~
