### ISSUE TITLE
建议优化项

### ISSUE THREAD

**Issue by HandsomeBoy01** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#140]
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/40994318/f7598108-5444-4c15-aa9a-3a376b8caa68)

类似于这种 客服发送，都是固定的字符串， 能够用枚举，而不用自己手写，这样可以增加开发效率

**Comment by fudiwei** [comment]
感谢建议。

也考虑过以常量的方式提供这些字符串。现阶段建议开发者自行定义常量。

**Comment by HandsomeBoy01** [comment]
> 感谢建议。
> 
> 也考虑过以常量的方式提供这些字符串。现阶段建议开发者自行定义常量。

好吧，也可以。感谢提供这么好的框架
