### ISSUE TITLE
SKIT.FlurlHttpClient.Wechat.TenpayV3 3.2.0 以上版本  JSAPI 下单失败

### ISSUE THREAD

**Issue by taoranxy** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#145]
---

**关于问题的简单描述**

SKIT.FlurlHttpClient.Wechat.TenpayV3 升级3.2.0以上版本后，提示下单失败，将其降回3.2.0及以下时，可正常调用。

---

**与问题相关的源代码**

```csharp
        /// <summary>
        /// 微信PC端下单
        /// </summary>
        /// <param name="description">商品描述</param>
        /// <param name="order">本地订单</param>
        /// <returns></returns>
        public async Task<Result<CreatePayTransactionNativeResponse>> WeChatCreatePayTransactionNative(string description, Order order)
        {
            var merchantId = _tenpayOptions.Merchants.FirstOrDefault()?.MerchantId;

            if (string.IsNullOrWhiteSpace(merchantId)) return new Result<CreatePayTransactionNativeResponse>("未查询到配置");

            var client = _tenpayHttpClientFactory.Create(merchantId);

            var request = new CreatePayTransactionNativeRequest()
            {
                OutTradeNumber = order.Number,
                AppId = _tenpayOptions.GZHAppId,
                Description = description,
                NotifyUrl = _tenpayOptions.NotifyUrl,
                Amount = new CreatePayTransactionNativeRequest.Types.Amount() { Total = (int)(order.ActualPayment * 100) }
            };
            var response = await client.ExecuteCreatePayTransactionNativeAsync(request, cancellationToken: _httpContextAccessor.HttpContext.RequestAborted);

            if (!response.IsSuccessful())
            {
                await Log.AddOperationalLog(GetUserId(), GetUserName(), "微信订单下单失败", $"JSAPI 下单失败（状态码：{response.GetRawStatus()}，错误代码：{response.ErrorCode}，错误描述：{response.ErrorMessage}）。");

                return new Result<CreatePayTransactionNativeResponse>("微信端下单失败,请联系管理员");
            }

            return new Result<CreatePayTransactionNativeResponse>(response);
        }
```

---

**异常堆栈或异常原因**

JSAPI 下单失败（状态码：400，错误代码：PARAM_ERROR，错误描述：输入源“/body/scene_info/payer_client_ip”映射到字段“用户终端IP”必填性规则校验失败，此字段为必填项）。

---

**Comment by fudiwei** [comment]
首先你调用的是 Native 下单接口，而不是 JSAPI 下单接口。

其次根据官方文档，这个字段是必填的：
> REF: https://pay.weixin.qq.com/docs/merchant/apis/native-payment/direct-jsons/native-prepay.html
> ![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/18504146/65554706-98cb-4db2-9583-4c81df102109)

**Comment by taoranxy** [comment]
写记录日志的时候搞错了，是调用的 Native 下单接口，我也查了官方的文档，之前的版本（3.2.0及以前）是可以正常调用并且返回支付链接参数code_url的，更新之后就无法正常调用了

**Comment by fudiwei** [comment]
> 我仔细查询了微信支付的官方文档，属性 payer_client_ip 是在 scene_info 参数下的，scene_info是选填参数，但模型 CreatePayTransactionNativeRequest 在初始化的时候会创建 Scene（即scene_info），不同的是 3.2.0以后的版本未对 ClientIp（即 payer_client_ip）进行赋值，导致下单失败 ![image](https://private-user-images.githubusercontent.com/46175134/341012344-2372fc4b-acf0-4416-bc31-cbf392e1e30b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTUyNDUsIm5iZiI6MTcxODc5NDk0NSwicGF0aCI6Ii80NjE3NTEzNC8zNDEwMTIzNDQtMjM3MmZjNGItYWNmMC00NDE2LWJjMzEtY2JmMzkyZTFlMzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDExMDIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MzE1ODRkM2RkNGNhMDZkNDk4OTAyYWZkN2JiNmFiNDM4YTRmYmEwM2UyMzJhZDI2ZTE1Yjk4MmFhMDM0OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LT4aVOdi-jc-zkvJpM94BsFrwQaBSn0LEWiJTKeh7dc) ![image](https://private-user-images.githubusercontent.com/46175134/341012393-8ec892d2-4140-46db-a873-affdab34ad73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3OTUyNDUsIm5iZiI6MTcxODc5NDk0NSwicGF0aCI6Ii80NjE3NTEzNC8zNDEwMTIzOTMtOGVjODkyZDItNDE0MC00NmRiLWE4NzMtYWZmZGFiMzRhZDczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDExMDIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlOTc3YWU0MWM2NTA2OTc4ZWExOGY3YmEwMmU1NzExMjgxYjgyNmUzMzYzYzg0NTIyMTcxYWViYTkyMjAwY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KL8I9aVEph08-gbbQI4mh7Ls_6PXtxmlyHVJdrUpPh0)

后续会将 `scene_info` 初值设为空。暂时可手动强制赋值为 null。

`payer_client_ip` 空字符串也能正常下单的问题已向官方反馈，后续应该会修复，建议按照规则传递正确的 IP 地址。

![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/18504146/014b297c-48f1-477d-a229-833e1a5a8afd)

**Comment by ZhangYiQiu** [comment]
> 首先你调用的是 Native 下单接口，而不是 JSAPI 下单接口。
> 
> 其次根据官方文档，这个字段是必填的：
> 
> > REF: https://pay.weixin.qq.com/docs/merchant/apis/native-payment/direct-jsons/native-prepay.html
> > ![image](https://private-user-images.githubusercontent.com/18504146/340990970-65554706-98cb-4db2-9583-4c81df102109.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNTM4ODIsIm5iZiI6MTcxOTE1MzU4MiwicGF0aCI6Ii8xODUwNDE0Ni8zNDA5OTA5NzAtNjU1NTQ3MDYtOThjYi00ZGIyLTk1ODMtNGM4MWRmMTAyMTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE0Mzk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NGRiZGIyODYwMGIzYzk4YWZiMjM4MDBjNDM2ZDUzNTNjZGQxZjE0YjZkMDRjMzY2YWY1NGQ0MWZkZWNlNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wR_zNYpiiJpEjS2HOhIbXLsZeSW-rDjQo3QvZ50q1kQ)

![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/22910338/8d1804a1-b43b-4cd4-9fa6-a0fe17103f0a)
这里的类型应该是可为空类型，不然因为你传递了`scene_info`字段，微信就会校验内部的`payer_client_ip`字段了

![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/22910338/16015474-0844-4a02-8dea-dd790479b689)
微信文档里`scene_info`字段也是非必填的
