### ISSUE TITLE
SubscribeMessagePopupEvent中的List可能是个对象

### ISSUE THREAD

**Issue by setli** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#147]
Hi fudiwei,
我们遇到个问题
订阅消息SubscribeMessagePopupEvent 在接收到微信发来的消息时中的List有可能是个对象 
![image](https://github.com/user-attachments/assets/fb15da08-0e13-4004-929c-0ce245601003)
而不是个数组对象 请问该如何兼容
期待您的答复
非常感谢!

相关链接https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/subscribe-message.html

**Comment by fudiwei** [comment]
emmm...微信这么奇葩么...

先当纯字符串处理吧，然后反序列化成 `Newtonsoft.Json.Linq.JToken`/`System.Text.Json.JsonElement` 之类的结构读取吧：

```csharp
var jsonDocument = JsonDocument.Parse(json);
var jsonList = jsonDocument.RootElement.GetProperty("List");
if (jsonList.ValueKind === JsonValueKind.Array)
{
   // is Array
}
else if (jsonList.ValueKind === JsonValueKind.Object)
{
   // is Object
}
```

后续版本更新的时候我加一下这里的反序列化兼容逻辑。

**Comment by setli** [comment]
感谢答复!
期待兼容的pr

**Comment by fudiwei** [comment]
Release [v3.5.0](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.Api/3.5.0) 已兼容两种结构，都会反序列化为列表。
