### ISSUE TITLE
CreatePayTransactionNative 支付返回值都是null，也没有报错信息

### ISSUE THREAD

**Issue by lycoris-xmin** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#149]
网页支付请求 Native 返回值都是空的，这是什么原因，也没有报错信息

![image](https://github.com/user-attachments/assets/521c4eba-75df-4a52-bc1d-48fb6dc7f144)

```
        public async Task<string> CreatePCPagePayAsync(OrderPayRequestDataModel input)
        {
            try
            {
                var config = await GetConfigurationAsync();

                var client = await _wechatApiClientFactory.CreateWechatTenpayClientAsync(config);

                var request = new CreatePayTransactionNativeRequest()
                {
                    AppId = config.AppId!,
                    OutTradeNumber = input.OrderNo,
                    Description = input.ProductName,
                    ExpireTime = DateTimeOffset.Now.AddMinutes(config.Pay.PayTimeExpire),
                    NotifyUrl = config.Pay.NotifyUrl!,
                    Amount = new CreatePayTransactionNativeRequest.Types.Amount() { Total = (int)(input.TotalAmount * 100) },
                    IsSupportFapiao = true,
                    Attachment = ""
                };

                _logger.Info($"wechatpay pc page request - {request.ToJson()}");

                var response = await client.ExecuteCreatePayTransactionNativeAsync(request, cancellationToken: _httpContextAccessor.HttpContext!.RequestAborted);

                _logger.Info($"wechatpay pc page response - {response.ToJson()}");

                if (!response.IsSuccessful())
                    throw new FriendlyException("跳转微信支付失败");

                return response.QrcodeUrl;
            }
            catch (Exception ex)
            {
                _logger.Error($"wechatpay pc page api request failed", ex);
                return "";
            }
        }
```

**Comment by fudiwei** [comment]
打印一下这两个值看是什么：

```csharp
Console.WriteLine(response.GetRawStatus());
Console.WriteLine(response.GetRawBytes());
```

**Comment by lycoris-xmin** [comment]
商户号非法，这微信沙箱环境测试真麻烦
能看到实际项内容就行，我还以为没有可以看到这些的方法。

具体问题，我自己再排查，谢谢

**Comment by fudiwei** [comment]
微信支付 v3 接口没有沙箱。你是把 v3 的参数传给 v2 的沙箱接口了吗？

**Comment by lycoris-xmin** [comment]
没有，v3走的正式环境404
![image](https://github.com/user-attachments/assets/3f45486c-bfc9-4ee4-bebe-58192d9d9f5a)
```
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

v2走的沙箱，沙箱获取密钥又都是
```
<xml>
    <return_code>
        <![CDATA[FAIL]]>
    </return_code>
    <return_msg>
        <![CDATA["mch_id" is required. "sign" is required. "nonce_str" is required]]>
    </return_msg>
</xml>
```

用postman都是这样，xml，json都是一样的返回值，把我整麻了

![image](https://github.com/user-attachments/assets/76706ecf-4356-4045-b89b-50ce7fa50129)

**Comment by fudiwei** [comment]
第一个 404 问题。请检查自己的服务器网络配置，有没有代理劫持之类的，或是代码里显式指定了 Proxy 或 Endpoint 之类的。你现在这返回的是个 nginx 的 404 页，而微信支付的后端根本也不是放在 nginx 后面的，这不是微信侧返回的错误，从哪儿返回来的你得自己排查一下了。

第二个 v2 沙箱问题。v2 和 v3 是两套完全独立的接口，你现在显然是拿着 v3 接口的参数去调用 v2 的沙箱了。因为 v2 接口出入参全都是 XML 格式的，而你传的是 JSON；且签名方式是 MD5 或 HMAC-SHA256，而你传的目测是 RSA 签名。

你要是想接入微信支付 v2 接口，你应该用 [TenpayV2](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.TenpayV2) 这个模块；你要是想接入微信支付 v3 接口，才应该用 [TenpayV3](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.TenpayV3) 这个模块。

**Comment by fudiwei** [comment]
第一个 404 问题。请检查自己的服务器网络配置，有没有代理劫持之类的，或是代码里显式指定了 Proxy 或 Endpoint 之类的。你现在这返回的是个 nginx 的 404 页，而微信支付 v3 的后端根本也不是放在 nginx 后面的，这不是微信侧返回的错误，从哪儿返回来的你得自己排查一下了。

第二个 v2 沙箱问题。v2 和 v3 是两套完全独立的接口，你现在显然是拿着 v3 接口的参数去调用 v2 的沙箱了。因为 v2 接口出入参全都是 XML 格式的，而你传的是 JSON；且签名方式是 MD5 或 HMAC-SHA256，而你传的目测是 RSA 签名。

你要是想接入微信支付 v2 接口，你应该用 [TenpayV2](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.TenpayV2) 这个模块；你要是想接入微信支付 v3 接口，才应该用 [TenpayV3](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.TenpayV3) 这个模块。

总而言之，再次强调，微信支付 v2 和 v3 是**两套完全独立**的接口，各自的文档不要混着看。SDK 里提供的也是各自独立的模块，不要混着用。

**Comment by lycoris-xmin** [comment]
好的 多谢，我再排查一下，有问题我再咨询，谢谢
