### ISSUE TITLE
同一个参数描述了不同的用途

### ISSUE THREAD

**Issue by LuohuaRain** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#15]
尊敬的开发者你好，我想知道 MerchantCertPrivateKey 到底是 **微信商户证书私钥** 还是 **微信商户 API 私钥**？
![image](https://user-images.githubusercontent.com/37979368/143769458-56f67109-abda-4cbf-ad17-0c7213912c02.png)
![image](https://user-images.githubusercontent.com/37979368/143769460-e3ee31f6-f38d-432c-9f87-4fd0aa756e17.png)

**Comment by fudiwei** [comment]
是一个意思哈。

提到“私钥”一定是指非对称加密算法，跟“公钥”相对。

微信商户平台里只有一种非对称算法，即 RSA。

**Comment by LuohuaRain** [comment]
意思是，**apiclient_key.pem** 和 **微信后台-API安全-设置API密钥** 这2个是同一种东西不同种形式，这样理解对吗？那我这里的参数是应该填哪个呢。感谢

**Comment by fudiwei** [comment]
不是噢，“密钥”是密钥，“私钥”是私钥。密钥是你说的“设置API密钥”(注意是 v3 的)，私钥是你这个 `key.pem`。

**Comment by fudiwei** [comment]
> [《腾讯客服 - 什么是 APIv3 密钥？》](https://kf.qq.com/faq/180830E36vyQ180830AZFZvu.html)
> [《腾讯客服 - 什么是 API 证书？》](https://kf.qq.com/faq/161222NneAJf161222U7fARv.html)

**Comment by LuohuaRain** [comment]
好的！ 因为之前用的paylink的支付sdk和SKIT的微信sdk. 这次想试试SKIT的支付SDK，发现paylink的参数和SKIT的好像还不太一样 所以被搞晕了哈哈。我还要深入学习一下，感谢指导！

**Comment by fudiwei** [comment]
其实要传的参数内容是一样的：

- 它的 `WeChatPayOptions.APIv3Key` 对应这里的 `WechatTenpayClientOptions.MerchantV3Secret`；
- 它的 `WeChatPayOptions.APIPrivateKey` 对应这里的 `WechatTenpayClientOptions.MerchantCertPrivateKey`。

只不过 Paylink 同时还支持了 V2 版的 API，有一些配置项是 V2 API 才需要的，如果不熟悉微信支付 API 的话确实容易混淆。

顺便问一句，你是已经有过应用了 Paylink 的生产项目在运行了吗？想更换其他 SDK 的原因是什么呢？

**Comment by LuohuaRain** [comment]
之前一个老项目是 paylink+SKIT，现在有个新的项目和之前方案差不多，所以想直接全套SKIT，这样精简一点，能少一个依赖就少一个依赖😂

**Comment by fudiwei** [comment]
> 之前一个老项目是 paylink+SKIT，现在有个新的项目和之前方案差不多，所以想直接全套SKIT，这样精简一点，能少一个依赖就少一个依赖😂

明白了。不过这个库只支持微信支付 V3 API，如果你有企业付款、红包、报关等少数几个目前只有 V2 API 的需求，可以继续使用 Paylink。

**Comment by LuohuaRain** [comment]
嗯好的，谢谢提醒！ 现在这个证书导入方案与paylink似乎有些不同，paylink 用的.p12 base64. SKIT好像我得把 apiclient_cert.pem 里的回车都去掉 然后复制出来。似乎还得写个工具一键去回车😂

**Comment by fudiwei** [comment]
如果你是以本地文件路径的方式导入，直接读取就好了：

```csharp
var options = new WechatTenpayClientOptions()
{
    MerchantCertPrivateKey = System.IO.File.ReadAllText("my_fake_path/apiclient_cert.pem")
};
```

只是 `appsettings.json` 里你只能写成一行的字符串罢了。

P.S. 去换行符很简单啊，随便找个支持正则替换的编辑器（比如 VSCode），把 `\r` 和 `\n` 都替换成就好了。甚至你在浏览器里打开开发者工具，直接复制粘贴就好了：

![image](https://user-images.githubusercontent.com/18504146/143818961-54b05e8b-fb08-456e-b08a-b9b23f5c7dbc.png)

**Comment by LuohuaRain** [comment]
啊哈，我竟然忘了这种方法！太感谢大佬了，刚才成功把jsapi下单跑通了！离成功又近了一步 yeah!
