### ISSUE TITLE
是否有较便捷的方式，统一管理AccessToken,让业务不涉及token

### ISSUE THREAD

**Issue by dongfo** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#150]
AccessToken通常为环境参数，受所在环境控制。
多小程序环境，
1.如果是自行开发，那么从统一的TokenManager取，业务不关心token，可以减少很多代码。
2.如果是在同一个程序中管理多个小程序，那么通过修改当前小程序环境上下文，可以使用统一的TokenManager，实现统一token管理。
3.如果是授权模式，同一个个三方平台管理多个小程序，其token来源有Authorize_acceccToken也可能有component accesstoken，可以通过额外的特性标注识别，TokenManager复杂一些，能够实现token的统一管理。

统一的token管理，减少调用接口所需的代码，减少业务对环境的感知。
我注意到目前调用接口的Executexx  均为扩展方法，难以使用依赖注入。HttpInterceptor远离原始参数，并且也不便于使用依赖注入。
似乎难以在接口中注入逻辑。

**Comment by fudiwei** [comment]
自定义一个工厂类，然后配合拦截器使用。

```csharp
// 伪代码
class MyFactory
{
  private readonly HttpClientFactory _httpClientFactory;

  public MyFactory (HttpClientFactory httpClientFactory)
  {
    _httpClientFactory = httpClientFactory;
  }

  public WechatApiClient CreateClient(string appId)
  {
    var options = GetMyWechatApiOptions(appId);
    return WechatApiClientBuilder
      .Create(options)
      .UseInterceptor(new MyAccessTokenInterceptor(appId)) // 拦截器还需要知道哪些参数也可以传进去
      .UseHttpClient(_httpClientFactory.Create(), false)
      .Build()
  }
}
```

**Comment by fudiwei** [comment]
关于这个问题我在一年多以前回答一位群友的提问时也提到过，现在再发出来，如果您有更好的想法也欢迎提出。

> 关于这个问题我解释一下，之前也有很多人问过这个问题。
> 
> 在设计之初我们也考虑过实现类似 TenpayV3 项目中的证书管理器的机制，来统一管理 AccessToken。比如像您提到的盛派，它有一个 AccessTokenContainer 的组件实现了自动化管理的功能。但在落地的时候发现了很多问题。
> 
> ------
> 
> 第一个问题是**如何满足多租户的业务需求**，即项目中有多个 AppId 需要管理，那么如何维护各自的 AccessToken。
> 
> 盛派对此的解决方式是通过 AppId+AppSecret 来区分，使用前需要在 AccessTokenContainer 注册。这个方案在早些年还比较完美，直到几年前，微信搞出了公众号/小程序服务商这种东西，事情开始变得复杂起来 —— AppId 和 AppSecret 都是平台方的，但调具体接口的时候却需要的是授权方的 AccessToken。此时单纯的 AccessTokenContainer 就玩不转了，盛派对此的解决方式是额外又引入了 ComponentContainer、AuthorizerContainer 两套组件。
> 
> 先抛开此时已有三套 AccessToken 管理组件的复杂设计问题，盛派这种方式还**有两个比较大的缺陷**。一是有部分接口是既支持使用平台方 AccessToken、又支持使用授权方 AccessToken 的，用不同的 AccessToken，会在返回数据上有所差异。盛派对此类接口是没有办法处理的，但好在此类接口比较少，所以社区里罕见有人提到此问题。二是这些 Container 都需要在使用前显式注册，而微信后来又增加了服务商可以直接开户的能力，也就是授权方是可以随时动态增加的。盛派也是没有办法处理这个问题的，只能是有新的授权方加入，就需要重启一遍项目。
> 
> 此外，盛派的这种 Container 机制你只能选择用或者不用，选择用的话其实它的内部逻辑是黑盒的，这对异构系统非常不友好。比如我们就存在大量由 PHP、Java 等其他语言开发的业务，它们也有中控 AccessToken 的需要。盛派的全自动化管理的方式，看似很傻瓜化，但一旦使用了，就只能**迫使你把所有项目全都变成“.NET+盛派”**。
> 
> 因此我们认为盛派的这种实现方式并非最优解。盛派因为有历史包袱在和兼容性需要所以只能设计成这样，我们可以理解。但我们经过内部研究后也没有发现哪种实现方式既能完美解决上述问题、又能让开发者上手成本低。
> 
> ------
> 
> 第二个问题是生产环境中绝大部分都是集群部署。而且即便是单机部署，也存在某种时刻可能有多个实例同时存在的可能（比如项目恰好重新部署或重启时、而代码恰好执行到了刷新 AccessToken 这步；或者你只有一个 AppId、但测试环境和生产环境都需要这个 AccessToken）。为了满足集群中控，势必需要一个集中存储的机制。而为了确保多实例不出现刷新冲突，还需要引入分布式锁机制。
> 
> 盛派对此的解决方式是抽象出 Domain Cache 这一层来，然后单独实现了 Redis/Memcached 两个模块来满足集中式存储和分布式锁的需要。
> 
> 但这**与我们的定位产生了矛盾**，本库只致力于 API 封装，而无论是集中式存储还是分布式锁，其实与 API 都无关。况且不是所有项目中都会用到 Redis/Memcached，盛派的这种解决方式反而提升了使用成本。
> 
> ------
> 
> 盛派确实是一个优秀的开源项目，我们也在 README 中指出它的功能是大而全的，但代价就是大大丧失了灵活性与轻便性。如果您需要的是一个开箱即用的“框架”，那么盛派是一个很好的选择。但我们并不想做一个框架。
> 
> 基于上面两个问题的考量，也因为本库的初心 —— 只做 Library（库）、不做 Framework（框架）。因此在经过各种权衡之后，我们最终选择了放弃实现内置一个 AccessToken 管理器的功能。
> 
> 虽然我们不会把这部分功能集成到到本库中，但同时我们也欢迎大家能基于 SKIT 二次开发出一套 AccessToken 中控机制的框架来，如果能开源分享出来就更好了 ♥

**Comment by dongfo** [comment]
我最初的设想是寻找一个切入点，允许外部注入自己的逻辑完成accessToken的填写。维护accesstoken依旧是类库外的任务，我希望更新accessToken在我的控制范围内，而不是类库。因为我会根据当前环境及配置取决定如何维护accessToken。

 HttpInterceptor的调用执行方式决定了他目前不方便使用依赖注入机制。如果有可能的话，我更希望依HttpInterceptor能够与IoC机制配合，赖一个抽象的接口，允许使用者根据自己的需求灵活替换实现，从而实现acceetoken的填写。

基于现状，我考虑实现一个静态类根据HttpInterceptor的入参取对应的accesstoken。

**Comment by fudiwei** [comment]
> HttpInterceptor的调用执行方式决定了他目前不方便使用依赖注入机制。如果有可能的话，我更希望依HttpInterceptor能够与IoC机制配合，赖一个抽象的接口，允许使用者根据自己的需求灵活替换实现，从而实现acceetoken的填写。

没有理解你的问题。HttpInterceptor 跟 IoC 既不耦合也不冲突，你想用 DI 来实例化 HttpInterceptor 也是可以的。

**Comment by dongfo** [comment]
我理解你的意思，在WechatApiClientFactory中Build()前完成注入即可。感谢你的耐心回答！
