### ISSUE TITLE
v2接口、请求和响应xml能原文输出吗？

### ISSUE THREAD

**Issue by fsinbad** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#153]
刚用这个SDK不是很清楚，找了文档和issue也没发现有人提。

请看一下，谢谢。

**Comment by fudiwei** [comment]
自定义拦截器，拦截器里可以获取到原始的 `HttpRequestMessage` 和 `HttpResponseMessage` 对象，你想怎么处理都行。

如果只是想获取响应的原始内容，每个 Response 对象都有一个 `GetRawBytes()` 方法是获取原始响应体的字节数组，你再 `Encoding.UTF8.GetString()` 一下就是 XML 了。

**Comment by fsinbad** [comment]
非常感谢，确实可以。
