### ISSUE TITLE
建议给程序集添加强名称

### ISSUE THREAD

**Issue by andywu188** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#154]
如果自己的项目使用了强名称，但依赖包没有强名称，会导致编译失败，
建议在.csproj文件中，加上

    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>../../key.snk</AssemblyOriginatorKeyFile>

**Comment by fudiwei** [comment]
上游依赖同样没有提供强名称。如有需要建议下载源码后自行编译。

**Comment by andywu188** [comment]
再向上游提建议 😂，必需要一级一级解决

**Comment by fudiwei** [comment]
这可太难了…… 😂
