### ISSUE TITLE
使用了SKIT.FlurlHttpClient.Wechat.TenpayV3,但是微信支付成功回调验签失败

### ISSUE THREAD

**Issue by 308224488** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#156]
使用了SKIT.FlurlHttpClient.Wechat.TenpayV3,但是微信支付成功回调验签失败
因为项目是4.6.1的，受框架影响只能安装了2.21.0版本。没有验签发方法。QueryCertificatesRequest用不了

**Comment by 308224488** [comment]
ExecuteQueryCertificatesAsync 也用不了

**Comment by fudiwei** [comment]
参照此文档打印错误信息看看：

> https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/archive/v2.x/docs/WechatTenpayV3/Basic_EventSignatureVerification.md#%E8%B0%83%E8%AF%95%E9%AA%8C%E7%AD%BE%E9%94%99%E8%AF%AF

P.S. 你可以切换到 `archive/v2.x` 分支上来查看 v2.x 版本的文档，主分支的文档只针对最新版本。

**Comment by fudiwei** [comment]
Issue 太久没有活跃，暂时关闭。如有需要，请重新打开。
