### ISSUE TITLE
微信小店订单详情接口有个字段类型错了

### ISSUE THREAD

**Issue by unetcore** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#160]
https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/1ce5ee4f6f646a64ad4fbe2d53dd6f064a268a9f/src/SKIT.FlurlHttpClient.Wechat.Api/Models/Channels/ECOrder/ChannelsECOrderGetResponse.cs#L820

![QQ_1729311993534](https://github.com/user-attachments/assets/91b6bd63-5f7e-44d4-92f9-60c743ec18ab)

是字符串类型

**Comment by fudiwei** [comment]
已修复。将随下一版本发布，敬请留意。
