### ISSUE TITLE
Failed to sign request. Please see the inner exception for more details. 

### ISSUE THREAD

**Issue by hallejuyahaha** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#162]
![image](https://github.com/user-attachments/assets/685114f1-87ff-4263-850d-c8277cf1ab3b)
这一行结果是空啊，获取不到CertificateManager，公钥application_cert怎么从本地配置进去啊？
现在的错是这个：Failed to sign request. Please see the inner exception for more details.

**Comment by fudiwei** [comment]
现在报错跟这里没关系，这里是验签用的。你要按指示看 InnerException 是什么？
