### ISSUE TITLE
[FEATURE] 微信小程序的短剧接口已经很久没更新了

### ISSUE THREAD

**Issue by cdbvv** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#163]
> **⚠⚠ 请注意：不符合格式要求的 Issue 可能会被直接关闭。**

---

**关于建议的简单描述**

/wxa/sec/vod/
微信小程序的短剧接口已经很久没更新了，很多接口字段对不上，小程序的接口文档字段增加了不少

---

**实现思路或解决方案**

如果你已有实现思路或解决方案，请在此贴出。

---

**补充说明**

请在此填写任何其他可以帮助说明的信息。

**Comment by fudiwei** [comment]
@cdbvv 能否提供一下涉及到变更的接口文档地址？微信官方没提供变更日志，我这里追踪起来比较困难。

**Comment by fudiwei** [comment]
[v3.6.0](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.Api/3.6.0) 已更新。
