### ISSUE TITLE
使用SKIT.FlurlHttpClient.Wechat.Api 2.37.0报错找不到方法

### ISSUE THREAD

**Issue by ShengSir1** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#170]
项目版本： .Net Framework 4.6.1
SKIT.FlurlHttpClient.Common 版本：3.0.0和3.1.0都试过
报错信息：
System.MissingMethodException
  HResult=0x80131513
  Message=找不到方法:“Int32 SKIT.FlurlHttpClient.ICommonResponse.get_RawStatus()”。
  Source=HostBLL
  StackTrace:
   在 HostBLL.ProjectBLL.PayWeiXinLogBLL.UploadShippingInfo(UploadShippingInfo_Input input) 在 D:\work2024\LvYun.Shop\SourceCode\接口\HostBLL\ProjectBLL\PayWeiXinLogBLL.cs 中: 第 871 行
   在 TH_Hospital_Web.Controllers.CommonController.UploadShippingInfo(UploadShippingInfo_Input input) 在 D:\work2024\LvYun.Shop\SourceCode\接口\HostWeb\Controllers\CommonController.cs 中: 第 554 行
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_3.<GetExecutor>b__3(Object instance, Object[] methodParameters)
   在 System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary2 arguments, CancellationToken cancellationToken)

**Comment by fudiwei** [comment]
duplicate #165
