### ISSUE TITLE
[BUG] V3.Sample_Net6 报错：ID为XX的进程未运行

### ISSUE THREAD

**Issue by AX0201** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#172]
---

**关于问题的简单描述**

如题。我填写了appsettings.json里的四个参数，然后运行，出现弹窗：ID为XX的进程未运行。
每次运行时弹窗中的ID值不同。
当我【生成】后手动运行exe时，无反应。

---

**与问题相关的源代码**

无，我没改代码，只填了json配置。

**异常堆栈或异常原因**

无
只有消息盒子弹窗：ID为XX的进程未运行

---

**发生问题的运行环境**

请在此填写以下几项内容：

1. 操作系统：windows10
2. .NET 版本：net6.0
3. 使用的模块及版本：SKIT.FlurlHttpClient.Wechat.TenpayV3.Sample_Net6
4. 其他环境信息：无

---

**补充说明**

无

**Comment by fudiwei** [comment]
启动端口改一个，应该是被占用了。
