### ISSUE TITLE
[FEATURE] 依赖的 SKIT.FlurlHttpClient.Common 版本太低，可以更新一下吗？

### ISSUE THREAD

**Issue by coolcalf** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#174]
依赖的 SKIT.FlurlHttpClient.Common 版本太低，与本系列相关包(如：DH.SKIT.FlurlHttpClient.ByteDance.MicroApp)冲突，请求更新。

**Comment by fudiwei** [comment]
你说的那个不是我发布的包……

**Comment by coolcalf** [comment]
谢谢，原来是我搞错了，下到了别人的二开版本....
