### ISSUE TITLE
小程序公众号的api都在一块?我只配置了小程序的appid,调用公众号的接口好像报错是不是这个原因导致?

### ISSUE THREAD

**Issue by laolaolulu** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#18]
> **⚠⚠ 请注意：不符合格式要求的 Issue 可能会被直接关闭。**

---

**关于建议的简单描述**

请在此简要描述你想要的功能。

---

**实现思路或解决方案**

如果你已有实现思路或解决方案，请在此贴出。

---

**补充说明**

请在此填写任何其他可以帮助说明的信息。

**Comment by fudiwei** [comment]
小程序的 AppId 只能调用允许小程序调用的那些接口；你不可能用一个小程序的 AppId 去调用一个公众号才有个接口啊，比如获取粉丝列表，小程序压根没有所谓的粉丝，你怎么能调通呢？

**Comment by fudiwei** [comment]
Issue 太久没有活跃，暂时关闭。如有需要，请重新打开。
