### ISSUE TITLE
issue about convert Pkcs8 keys to byte arrays

### ISSUE THREAD

**Issue by anranruye** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#2]
https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/665efdfc9719029cf6f14cacab2bb35f457bebea/src/SKIT.FlurlHttpClient.Wechat.TenpayV3/Utilities/RSAUtility.cs#L230

A mistake? Do you intend to use `Regex.Replace(publicKey, @"\s+", "")` ？

https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/665efdfc9719029cf6f14cacab2bb35f457bebea/src/SKIT.FlurlHttpClient.Wechat.TenpayV3/Utilities/RSAUtility.cs#L219 

And here is the same issue

**Comment by fudiwei** [comment]
My mistake 😭

Thanks for your correction.

Anyway, there will be no problem now if you directly use the certificate files provided by Tenpay. So I will not release a new version to NuGet, only fix the code currently.

BTW, I'm from Dalian as also. Bro 😁

**Comment by fudiwei** [comment]
Fix this on release v1.4.0
