### ISSUE TITLE
为何没有服务商版的demo

### ISSUE THREAD

**Issue by ynanech** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#22]
如题，可以提供一下吗

**Comment by fudiwei** [comment]
服务商跟直连商户没啥特殊的区别啊……只不过部分接口（比如下单、退款等）服务商需要额外传一个 `SubMerchantId` 参数而已、直连商户则不需要，另外服务商还有一些特殊的接口可以调用（比如进件、分账等），但二者在使用方式上没有任何区别。

请问你是哪里没太弄懂呢？

**Comment by ynanech** [comment]
![image](https://user-images.githubusercontent.com/20282409/147490368-6d865c1f-d122-4cd2-ace6-80c1bcf8f21c.png)
服务商版client初始化时传入的是sp_mchid还是sub_mchid

**Comment by fudiwei** [comment]
不一定，看你的业务需要。

Client 初始化所需要的配置参数（商户号、API 密钥、证书序列号、私钥等等）是用于请求签名的，谁发起请求就用谁的。想通过服务商代下单那就用服务商的相应参数；想子商户自己下单那就用子商户的相应参数。

P.S. 如果电商收付通之类的业务，子商户不能自己发起请求，必须通过服务商。
