### ISSUE TITLE
昨天更新到了最新版本，实现了几个常用功能，启动报以下问题是什么原因

### ISSUE THREAD

**Issue by ynanech** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#25]
System.Reflection.ReflectionTypeLoadException:“Unable to load one or more of the requested types.
Method 'set_RawStatus' in type 'SKIT.FlurlHttpClient.Wechat.Api.Models.SnsJsCode2SessionResponse' from assembly 'SKIT.FlurlHttpClient.Wechat.Api, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'set_RawStatus' in type 'SKIT.FlurlHttpClient.Wechat.Api.Models.SnsOAuth2AccessTokenResponse' from assembly 'SKIT.FlurlHttpClient.Wechat.Api, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'set_RawStatus' in type 'SKIT.FlurlHttpClient.Wechat.Api.Models.SnsJsCode2SessionResponse' from assembly 'SKIT.FlurlHttpClient.Wechat.Api, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'set_RawStatus' in type 'SKIT.FlurlHttpClient.Wechat.Api.Models.SnsOAuth2AccessTokenResponse' from assembly 'SKIT.FlurlHttpClient.Wechat.Api, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'set_RawStatus' in type 'SKIT.FlurlHttpClient.Wechat.Api.Models.CgibinTokenResponse' from assembly 'SKIT.FlurlHttpClient.Wechat.Api, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'set_RawStatus' in type 'SKIT.FlurlHttpClient.Wechat.Api.Models.CgibinTicketGetTicketResponse' from assembly 'SKIT.FlurlHttpClient.Wechat.Api, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'set_RawStatus' in type 'SKIT.FlurlHttpClient.Wechat.Api.Models.CgibinTokenResponse' from assembly 'SKIT.FlurlHttpClient.Wechat.Api, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'set_RawStatus' in type 'SKIT.FlurlHttpClient.Wechat.Api.Models.CgibinTicketGetTicketResponse' from assembly 'SKIT.FlurlHttpClient.Wechat.Api, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.”

**Comment by fudiwei** [comment]
如果是 .NET Framework 项目，请不要手动升级 `SKIT.FlurlHttpClient.Common` 这个依赖，安装 `SKIT.FlurlHttpClient.Wechat.Api` 时是什么版本就是什么版本就可以了。 

如果是 .NET Core 项目，请不要手动添加 `SKIT.FlurlHttpClient.Common` 这个依赖，移除或降级回上一个版本即可。

**Comment by ynanech** [comment]
![image](https://user-images.githubusercontent.com/20282409/148712690-ec2c9025-6355-46bc-9353-fa47ef9ff55e.png)
我检查了一下，没有引用，我的是.net core6

**Comment by ynanech** [comment]
![image](https://user-images.githubusercontent.com/20282409/148712769-5c733ff4-824e-4068-aef4-99ec41e53b82.png)
我没有手动添加SKIT.FlurlHttpClient.Common,我的是.net core6项目

**Comment by ynanech** [comment]
之前是正常的，就因昨天我加入了支付
我的Api项目引用了Server项目
Api项目引入了SKIT.FlurlHttpClient.Wechat.Api
Server项目引入了SKIT.FlurlHttpClient.Wechat.TenpayV3
是不是和这个有关
![image](https://user-images.githubusercontent.com/20282409/148713514-423c64fe-8c99-4d80-854e-c0f3b523da5a.png)

**Comment by fudiwei** [comment]
啊，那我知道了，确实和这个有关。这两个模块依赖的 `SKIT.FlurlHttpClient.Common` 公共库版本不一致，所以依赖冲突了。

你可以先把 `SKIT.FlurlHttpClient.Wechat.TenpayV3` 降级回 2.2.X。

稍后我会重新发布一个新的 `SKIT.FlurlHttpClient.Wechat.Api`，对齐各个模块的公共库版本，你看到有新版本提示了再都更新回来吧。

**Comment by ynanech** [comment]
ok

**Comment by fudiwei** [comment]
可以升级了~

**Comment by fudiwei** [comment]
可以升级了~

**Comment by ynanech** [comment]
好的，正常了
