### ISSUE TITLE
企业微信提供了微信客服的API，大神空闲时可以考虑更新一下，谢谢

### ISSUE THREAD

**Issue by xiazhangch** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#33]
RT，这个接口比较有用，可以考虑一下，谢谢！

**Comment by fudiwei** [comment]
你是说这部分吗？https://developer.work.weixin.qq.com/document/path/94662

目前都已经支持了的，哪个地方需要更新？

**Comment by fudiwei** [comment]
![image](https://user-images.githubusercontent.com/18504146/151094755-d2f45c8c-be40-4323-b694-73ee87e00a95.png)

**Comment by xiazhangch** [comment]
> ![image](https://user-images.githubusercontent.com/18504146/151094755-d2f45c8c-be40-4323-b694-73ee87e00a95.png)

谢谢大神，之前没注意到，确实是有的。感谢、感谢！

**Comment by fudiwei** [comment]
[《开发文档 - 如何快速找到需要调用的 API 模型类名 / 方法名？》](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/main/docs/WechatWork/Advanced_ModelDefinition.md)
