### ISSUE TITLE
NetCore5.0出错

### ISSUE THREAD

**Issue by XRJ1230663** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#34]
> **⚠⚠ 请注意：不符合格式要求的 Issue 可能会被直接关闭。**

---

**关于问题的简单描述**

请在此填写你遇到的问题。
Specified argument was out of the range of valid values. (Parameter 'cancellationToken')
---

**与问题相关的源代码**

await client.ExecuteCreatePayTransactionAppAsync(request,cancellationToken)

```csharp
// Source Code
```

---

**异常堆栈或异常原因**

请在此填写你遇到的问题抛出错误时的异常消息和堆栈跟踪（如果有的话）。

---

**发生问题的运行环境**

请在此填写以下几项内容：

1. 操作系统：请填写发生问题的操作系统环境信息（如：Windows Server 2012 R2）
2. .NET 版本：请填写发生问题的 .NET 环境信息（如：.NET Framework 4.7.2 / .NET 5.0）
3. 使用的模块及版本：请填写发生问题的模块信息（如：SKIT.FlurlHttpClient.Wechat.Api 1.0.0）
4. 其他环境信息。

---

**补充说明**

请在此填写任何其他可以定位问题的信息。

**Comment by fudiwei** [comment]
问题已修复，请升级 `Common` 库到 v2.3.2+ 版本。
