### ISSUE TITLE
WxBizMsgCryptor.VerifySignature 会有验证失败的情况

### ISSUE THREAD

**Issue by MoondanceZ** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#4]
`            
      ISet<string> set = new SortedSet<string>();

            set.Add(sToken);

            set.Add(sTimestamp);

            set.Add(sNonce);

            set.Add(sMsgEncrypt); 
`, 换回官方实例中的代码, 验证通过

**Comment by fudiwei** [comment]
方便给的可复现的例子吗？我这的单测是没问题的。

**Comment by fudiwei** [comment]
方便给个可复现的例子吗？我这的单测是没问题的。

**Comment by fudiwei** [comment]
另外请问是哪个模块？是公众号的还是企业微信的？

**Comment by MoondanceZ** [comment]
微信开放平台的授权事件接受回调接口, 这个不是百分之百复现的
{
  "msg_signature": "9b64d1054af563fbd8fdea6ec9017b10d2a7933c",
  "timestamp": "1628737717",
  "nonce": "1811081856",
  "callbackXml": "<xml>\n    <AppId><![CDATA[wx2b85f04c1d6fef81]]></AppId>\n    <Encrypt><![CDATA[Q/jUxIL3/jRaFeTKesIr1QSq2SOEApDqlzcRrRM6Jlk4EbMBns3plPOR/W3gThOEq+zYI42fNSoIUb3cQwt9zyD1aLU/7D3WNLute7LQ9LSHjZEfVmx5zcIR9zvrUWGjhe1whTPH4e1WR6vbOYs8o/bDRF0vX/NcE4XK7P83Y6CzQiJoKbjVCne84s0zcw5eh+ZUDB55eaDHPSoS7kAC8kB00pfBoDF0jyfc8CUKLW97e72vJGyUWjZ0BvYN+R+tFjMgEzg/EN1imuuFnf40DMAcvB6y+C97TuaWjpgfRdowGWzn10JAFNukRfQqjdA0e2bfczJ7+t9w/t8/XSMADJOt1xbnP+I5cRX/r7ueBGmG/6ejP3myO9yTXHdujGvwrXHuWw+J7qD4VoUVjbm2vQ1qQKbrweKssr6O+3XSbanZ5R3n26EpN/gfgX+r6rcGViqsFop9Ai9xMnfJUubB6Q==]]></Encrypt>\n</xml>\n"
}

**Comment by MoondanceZ** [comment]
<xml>
  <AppId><![CDATA[wx2b85f04c1d6fef81]]></AppId>
  <Encrypt><![CDATA[Q/jUxIL3/jRaFeTKesIr1QSq2SOEApDqlzcRrRM6Jlk4EbMBns3plPOR/W3gThOEq+zYI42fNSoIUb3cQwt9zyD1aLU/7D3WNLute7LQ9LSHjZEfVmx5zcIR9zvrUWGjhe1whTPH4e1WR6vbOYs8o/bDRF0vX/NcE4XK7P83Y6CzQiJoKbjVCne84s0zcw5eh+ZUDB55eaDHPSoS7kAC8kB00pfBoDF0jyfc8CUKLW97e72vJGyUWjZ0BvYN+R+tFjMgEzg/EN1imuuFnf40DMAcvB6y+C97TuaWjpgfRdowGWzn10JAFNukRfQqjdA0e2bfczJ7+t9w/t8/XSMADJOt1xbnP+I5cRX/r7ueBGmG/6ejP3myO9yTXHdujGvwrXHuWw+J7qD4VoUVjbm2vQ1qQKbrweKssr6O+3XSbanZ5R3n26EpN/gfgX+r6rcGViqsFop9Ai9xMnfJUubB6Q==]]></Encrypt>
</xml>

**Comment by fudiwei** [comment]
Token 变了那签名一定对不上的呀 😂

不方便透露的话能方便断点调试一下，看一下最后拼出来的待签名数据、以及最后的签名结果是什么吗？

微信给的例子是此处：

```csharp
/* WXBizMsgCrypt.cs 第 206 行起 */
sha = new SHA1CryptoServiceProvider();
enc = new ASCIIEncoding();
byte[] dataToHash = enc.GetBytes(raw); // 这里打一下断点，看一下 raw
byte[] dataHashed = sha.ComputeHash(dataToHash);
hash = BitConverter.ToString(dataHashed).Replace("-", "");
hash = hash.ToLower(); // 这里也打一下断点，看一下 hash
```

本库的代码是此处：

```csharp
/* WxBizMsgCryptor.cs 第 240 行起 */
string rawText = string.Join(string.Empty, set.ToArray()); // 这里打一下断点，看一下 rawText
string signText = Security.SHA1Utility.Hash(rawText); // 这里打一下断点，看一下 signText
return signText.ToLower();
```

**Comment by MoondanceZ** [comment]
不是这个问题 , Hash是没问题的, 是一楼贴的代码那里 , 得到的顺序跟微信官方示例中生成的顺序不一样

**Comment by fudiwei** [comment]
所以我想说看一下 `raw` 那里拼接的问题呀~ 😂

**Comment by MoondanceZ** [comment]
给我的Token开头给你
`ovAkP0Tb`
套进去试一下就能发现问题😂

**Comment by fudiwei** [comment]
谢谢，发现不一致的地方了。

```csharp
// 微信签名结果
raw1 = "16287377171811081856Q/jUxIL3/jRaFeTKesIr1QSq2SOEApDqlzcRrRM6Jlk4EbMBns3plPOR/W3gThOEq+zYI42fNSoIUb3cQwt9zyD1aLU/7D3WNLute7LQ9LSHjZEfVmx5zcIR9zvrUWGjhe1whTPH4e1WR6vbOYs8o/bDRF0vX/NcE4XK7P83Y6CzQiJoKbjVCne84s0zcw5eh+ZUDB55eaDHPSoS7kAC8kB00pfBoDF0jyfc8CUKLW97e72vJGyUWjZ0BvYN+R+tFjMgEzg/EN1imuuFnf40DMAcvB6y+C97TuaWjpgfRdowGWzn10JAFNukRfQqjdA0e2bfczJ7+t9w/t8/XSMADJOt1xbnP+I5cRX/r7ueBGmG/6ejP3myO9yTXHdujGvwrXHuWw+J7qD4VoUVjbm2vQ1qQKbrweKssr6O+3XSbanZ5R3n26EpN/gfgX+r6rcGViqsFop9Ai9xMnfJUubB6Q==ovAkP0Tb";
sign1 = "8128e41a38892d814e4aa67753425da9dc8ec2b3";

// 本库签名结果
raw2 = "16287377171811081856ovAkP0TbQ/jUxIL3/jRaFeTKesIr1QSq2SOEApDqlzcRrRM6Jlk4EbMBns3plPOR/W3gThOEq+zYI42fNSoIUb3cQwt9zyD1aLU/7D3WNLute7LQ9LSHjZEfVmx5zcIR9zvrUWGjhe1whTPH4e1WR6vbOYs8o/bDRF0vX/NcE4XK7P83Y6CzQiJoKbjVCne84s0zcw5eh+ZUDB55eaDHPSoS7kAC8kB00pfBoDF0jyfc8CUKLW97e72vJGyUWjZ0BvYN+R+tFjMgEzg/EN1imuuFnf40DMAcvB6y+C97TuaWjpgfRdowGWzn10JAFNukRfQqjdA0e2bfczJ7+t9w/t8/XSMADJOt1xbnP+I5cRX/r7ueBGmG/6ejP3myO9yTXHdujGvwrXHuWw+J7qD4VoUVjbm2vQ1qQKbrweKssr6O+3XSbanZ5R3n26EpN/gfgX+r6rcGViqsFop9Ai9xMnfJUubB6Q==";
sign2 = "eb250e4c7a9d54f28004ff5ad1f6d92f6bfc92e7";
```

看起来微信是把 Token 拼在了结尾，并不是普通的按 ASCII 排序，我一直以为是按 ASCII 排序的，现在看来并不是。

官方文档对签名过程的解释如图：

![image](https://user-images.githubusercontent.com/18504146/129176456-496a8505-0111-4634-be53-e5caad8eb61d.png)

具体怎么排序的我今晚跟踪一下。

P.S. 实在是不想照搬官方给的那个一看就是从 Java 翻译过来的示例代码 😂

**Comment by MoondanceZ** [comment]
同感呀, 看着JAVA翻译过来的代码确实很蛋疼
直接套用微信官方那个版本还有个很诡异的问题,  系统内存会不断飙升
后面改成用你的代码内存就正常了😊

**Comment by fudiwei** [comment]
方便再给一个你那验签正常的例子吗？我对比一下有啥不一样的。

**Comment by MoondanceZ** [comment]
{
  "msg_signature": "433916a86b50e917d27cac1b175dc007b2a2b725",
  "timestamp": "1628738307",
  "nonce": "286477959",
  "encrypt": "3eSQ2p6lI6a1c6LY73RNlMZt/GCdTxavY8zIxOEJAbifCXrHCAMQFQsLQQqqhNy8DDfPuphQIhndJxlhhW1w2n13+DfLl2T1nVPsNTZKhU4uxXkZCcJKpztx7Z7TrWR6gmNdTCS/4CTHmuvv7C8JO+f8yxxm9bgoaBumo7JErKjVW0Wgkom/evN4yoMCz6C2WpKCnxKik2CRQ/Wcb8fTlQ4YDp6iHDApvmYPJMV4LgI5aYPm/K+uqQMChFQ3ZiPhhjsZvFIfiotDXQT3x3HvKJN+dKrGOXqbDjpiFxByH5AbHH4fHgsvMWlNqK5SFnuL+4jPhrNT/MwwmArgkcCEZBJrV157WUMLMc4aoxuMJF1ueLAti0uuAp0AxHRG8HfQ2a7d/O4td2jRzD93Rlmtg9kscK315DaN2erHNl7Nlp4rdJ2yuzLtnU9PXFLp0CainQ1rzuOJEHt4tnE1fpQ9GQ=="
}

**Comment by fudiwei** [comment]
找到问题了，`SortedSet` 如果不指定构造函数的第一个参数 `comparer`，默认值将使用 `StringComparer.CurrentCulture`，在中文操作系统上会导致排序表现不一致，反而在英文操作系统上没有此问题。

修改方式：强制指定该参数值为 `StringComparer.Ordinal`。

稍晚一些的时候我会发布一个新版本到 NuGet 上。

**Comment by fudiwei** [comment]
Fix this on [release v1.4.1](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.Api/1.4.1).
