### ISSUE TITLE
企业微信临时素材，发送时中文乱码各位有遇到的吗？

### ISSUE THREAD

**Issue by kinglinglive** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#40]
请简要描述你所遇到的问题。
![24bf7c81213c10b0f4b489d96e09f28](https://user-images.githubusercontent.com/50543168/164584885-566f60b1-f071-4cb7-81fc-a293ba39b221.jpg)

**Comment by fudiwei** [comment]
麻烦看一下更新到 [v2.7.2-alpha.1](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.Work/2.7.2-alpha.1) 版本（VS 中 NuGet 管理器需勾选“包括预发行版本”），重新上传一下素材，看一下是否还有这个问题？

如果能解决的话我再推到主干分支上去。

**Comment by kinglinglive** [comment]
![9e691ddb1b44095c99b508fff00d083](https://user-images.githubusercontent.com/50543168/164621162-3a79acdd-d3b4-4ceb-9051-fd8a7f8546bd.jpg)
还不对大佬，名字变了

**Comment by fudiwei** [comment]
看起来 `System.Net.Http.MultipartFormDataContent` 会强制 URL Encode 非 ASCII 字符（你的第一张截图里不是乱码、而是 URL 编码后的结果），我再研究研究看看。

**Comment by fudiwei** [comment]
@kinglinglive 麻烦再试一下 [v2.7.2-alpha.2](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.Work/2.7.2-alpha.2) 这个版本。

**Comment by kinglinglive** [comment]
@fudiwei 可以了，感谢
![0ff9100b5d201dbed71c3a3ec72abd2](https://user-images.githubusercontent.com/50543168/164685265-918456b9-6f9b-433c-bffe-3f272331461a.jpg)

**Comment by fudiwei** [comment]
这样看起来微信的服务器并没有遵守 RFC-7578 的有关规范。 😂

**Comment by fudiwei** [comment]
Fix this on release [v2.7.2](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.Work/2.7.2).
