### ISSUE TITLE
可以增加一个对支付通知的解密吗

### ISSUE THREAD

**Issue by DreamTom** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#53]
---

**关于建议的简单描述**

支付宝的sdk有提供一个通知的验签，你这个可以提供一个吗，哈哈

---

**实现思路或解决方案**

---

**补充说明**

**Comment by fudiwei** [comment]
有的，请看开发文档。

![image](https://user-images.githubusercontent.com/18504146/185657931-fffb518b-6d6b-47ba-aa7f-8ab7265788e4.png)
