### ISSUE TITLE
企业微信汇报详情接口缺少文档Id

### ISSUE THREAD

**Issue by sofm13** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#62]
查看源代码是继承的OA审批的基类，但是汇报的控件有多一个文档控件附16 文档控件（control参数为Doc）

**Comment by fudiwei** [comment]
请直接提供接口或模型名称，否则接口太多了，我不知道你说的是哪个。

**Comment by sofm13** [comment]
接口地址https://qyapi.weixin.qq.com/cgi-bin/oa/journal/get_record_detail?access_token=ACCESS_TOKEN
模型名称CgibinOAJournalGetRecordDetailResponse，/cgi-bin/oa/journal/get_record_detail 接口的响应。
其中ApplyData.Contents.Control字段 缺少文档控件（control参数为Doc）

**Comment by fudiwei** [comment]
已在 [v2.12.0](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.Work/2.12.0) 中追加。
