### ISSUE TITLE
[BUG] V2 付款码接口响应类存在风格不一致的命名

### ISSUE THREAD

**Issue by gehongyan** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#66]
**关于问题的简单描述**

商户退款单号字段在整个仓库中都被命名为 `OutRefundNumber`，而在 `SKIT.FlurlHttpClient.Wechat.TenpayV2.Models.GetPayRefundResponse.Types.Refund` 中的 `商户退款单号` 被命名为 `OutRefundId`，建议在下一次允许破坏性变更的版本中调整命名为统一的名称 `OutRefundNumber`。

---

**与问题相关的源代码**

[SKIT.FlurlHttpClient.Wechat.TenpayV2.Models.GetPayRefundResponse.Types.Refund.OutRefundId](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/main/src/SKIT.FlurlHttpClient.Wechat.TenpayV2/Models/Pay/GetPayRefundResponse.cs#L21)

**Comment by fudiwei** [comment]
感谢建议
