### ISSUE TITLE
[FEATURE] 是否考虑移除Cgibin前缀？

### ISSUE THREAD

**Issue by Rwing** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#7]
如题，cgi-bin并不是指某特定的api，详见

https://www.zhihu.com/question/21432096

**Comment by fudiwei** [comment]
也没说它指特定的 API 啊 😂

接口模型的命名是与地址保持一致的，地址是 `/cgi-bin/ticket/get-ticket` 的接口模型也就是 `CgibinTicketGetTicket`。当然也不是 `cgi-bin` 开头的，比如 `/sns/jscode2session` 对应的模型就是 `SnsJsCode2Session`，`/wxa/getwxacode` 对应的模型就是 `WxaGetWxaCode`。

这是为了便于开发者看微信的接口文档时，就能快速地知道在本库里对应的模型是哪个。毕竟有上千个 API 呢，没有规律全靠人脑记住可太难了。

这一点我在开发文档中也有写到：
> [《如何快速找到需要调用的 API 模型类名 / 方法名？》](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/main/docs/WechatApi/Advanced_ModelDefinition.md)

所以您想去除这个前缀的目的是？

**Comment by Rwing** [comment]
因为cgi-bin并不是腾讯或者微信独有的，凡是使用cgi编程都会有cgi-bin目录
例如百度也有可能有 http://baidu.com/cgi-bin/xxxx
王者荣耀也可能有 http://wzry.qq.com/cgi-bin/xxxx
这样的话，cgi-bin就变得没有意义了，不如不加。

**Comment by fudiwei** [comment]
感觉并没有说服我 😂

因为我在设计时压根没想过它是什么“前缀”，跟语言也好、API 到底怎么实现的也罢，我其实没关心，**我只是单纯的把 API 地址转换为大驼峰形式罢了，至于它原本开头就带着 `cgi-bin`，那也不是我能控制的呀**。

P.S.1 其实据我所知很多微信接口并非是 CGI 实现的，有大把的 Java 甚至 PHP 写的接口，只是微信的开发人员会在网关层配置路由时习惯性的往 `cgi-bin` 目录下配，我猜可能是习惯成自然，早期确实是 C++ 团队在写 CGI 接口，后来人照猫画虎也没管为啥带个 `cgi-bin` 就也一股脑儿往下面放了。

P.S.2 如果真的有一个 API 是 `/csharp/user/info`，模型当然也会是 `CSharpUserInfo`，但还是那句话，这里的 `CSharp` 跟语言无关，只是把地址变成大驼峰了，有它没它，都只是巧合而已。

P.S.3 其实如果所有的 API 地址开头都是 `cgi-bin` 也就好了，我就会把这部分放到 `Endpoints` 里，在模型上就可以都不用带 `Cgibin` 了。问题是并非所有 API 都在 `cgi-bin` 下，比如前面我提到的那两个 API。所以你说如果一种的全都去掉所谓“前缀”、另外几种都不去掉，是不是也很奇怪呢？

**Comment by fudiwei** [comment]
还有更重要的一点您没考虑到：那就是这个库已经有很多项目投入使用了，也不仅仅是我公司的，很多社区的朋友也在用了。

您提出的这一点变化，并没有带来新功能、也并非优化了使用流程或提升性能，仅仅是重命名了几个类而已，还不是 typo 这种拼写错误导致的。

这种情况下，您觉得是否应该引入这么大 Breaking Changes 呢？毕竟 `cgi-bin` 开头的 API 可有近千个。

**Comment by fudiwei** [comment]
Issue 太久没有活跃，暂时关闭。如有需要，请重新打开。
