### ISSUE TITLE
遗失[WechatTenpaySensitive]

### ISSUE THREAD

**Issue by zxfwinder** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#76]
https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/17ad48dd54e094a30a6ae8f66602d95193f5e26d/src/SKIT.FlurlHttpClient.Wechat.TenpayV3/Models/PayrollCard/CreatePayrollCardTokenRequest.cs#L6

**Comment by fudiwei** [comment]
Fix this on release [v2.15.2](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.TenpayV3/2.15.2).
