### ISSUE TITLE
[BUG] 酒店押金退款接口响应类缺失商户退款单号属性

### ISSUE THREAD

**Issue by gehongyan** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#82]
**关于问题的简单描述**

酒店押金退款接口响应类 `CreateDepositRefundResponse` 缺失映射 `out_refund_no` 字段的商户退款单号属性 `OutRefundNumber`。

参考 [微信支付酒店押金申请退款文档] 中的返回结果部分，可以发现，该接口应返回字段 `out_refund_no`，但该文档的响应示例中缺失了该字段。在实际测试调用 `/deposit/refund` 接口时观察响应结果，可以发现`out_refund_no` 字段是存在的。

实际测试调用结果（敏感信息已用星号代替）：

```xml
<xml>
        <return_code><![CDATA[SUCCESS]]></return_code>
        <result_code><![CDATA[SUCCESS]]></result_code>
        <appid><![CDATA[wx1ade********]]></appid>
        <mch_id><![CDATA[15********]]></mch_id>
        <sub_mch_id><![CDATA[15********]]></sub_mch_id>
        <nonce_str><![CDATA[hiAK********]]></nonce_str>
        <sign><![CDATA[06250F************************************************]]></sign>
        <transaction_id><![CDATA[4200********************************]]></transaction_id>
        <out_refund_no><![CDATA[DEMO************************]]></out_refund_no>
        <refund_id><![CDATA[5030************************]]></refund_id>
        <refund_fee>1</refund_fee>
        <total_fee>2</total_fee>
        <fee_type><![CDATA[CNY]]></fee_type>
        <coupon_refund_fee>0</coupon_refund_fee>
</xml>
```

---

**与问题相关的源代码**

酒店押金退款接口响应类 [`SKIT.FlurlHttpClient.Wechat.TenpayV2.Models.CreateDepositRefundResponse`]

[微信支付酒店押金申请退款文档]: https://pay.weixin.qq.com/wiki/doc/api/deposit_sl.php?chapter=27_5&index=10
[`SKIT.FlurlHttpClient.Wechat.TenpayV2.Models.CreateDepositRefundResponse`]: https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/f059387edcaa0448c8161166839355bd8e389490/src/SKIT.FlurlHttpClient.Wechat.TenpayV2/Models/Deposit/CreateDepositRefundResponse.cs#L49

**Comment by gehongyan** [comment]
类似的问题也发生在 [酒店押金查询退款] 接口上。

酒店押金退款接口 `/deposit/refundquery` 不支持查询单笔冻结交易的所有退款交易，文档给出的示例不正确。

酒店押金退款接口响应类 [SKIT.FlurlHttpClient.Wechat.TenpayV2.Models.GetDepositRefundResponse] 缺失映射 `out_refund_no` 字段的商户退款单号属性 `OutRefundNumber`，缺失映射 `refund_id` 字段的微信退款单号属性 `RefundId`。

当前存在的属性 `RefundList` 无法正常映射，实际结果为 `null`。

![image](https://user-images.githubusercontent.com/21241496/222356989-7f00352e-a7de-41c7-982f-02f00ca557b8.png)

实际测试调用结果（敏感信息已用星号代替）：

```xml
<xml>
          <return_code><![CDATA[SUCCESS]]></return_code>
          <result_code><![CDATA[SUCCESS]]></result_code>
          <appid><![CDATA[wx1a************]]></appid>
          <mch_id><![CDATA[1515********]]></mch_id>
          <sub_appid><![CDATA[]]></sub_appid>
          <sub_mch_id><![CDATA[152********]]></sub_mch_id>
          <nonce_str><![CDATA[0t1K************]]></nonce_str>
          <sign><![CDATA[51D8C0093****************************************]]></sign>
          <transaction_id><![CDATA[4200************************]]></transaction_id>
          <out_trade_no><![CDATA[DEMO****************]]></out_trade_no>
          <total_fee>10</total_fee>
          <settlement_total_fee>2</settlement_total_fee>
          <fee_type><![CDATA[CNY]]></fee_type>
          <out_refund_no><![CDATA[DEMO****************]]></out_refund_no>
          <refund_id><![CDATA[503****************************]]></refund_id>
          <refund_fee>2</refund_fee>
          <refund_status><![CDATA[SUCCESS]]></refund_status>
</xml>
```



[酒店押金查询退款]: https://pay.weixin.qq.com/wiki/doc/api/deposit_sl.php?chapter=27_6&index=11
[SKIT.FlurlHttpClient.Wechat.TenpayV2.Models.GetDepositRefundResponse]: https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/f059387edcaa0448c8161166839355bd8e389490/src/SKIT.FlurlHttpClient.Wechat.TenpayV2/Models/Deposit/GetDepositRefundResponse.cs

**Comment by fudiwei** [comment]
感谢反馈。

P.S. 【吐槽时刻】这么多年了微信就不知道改改文档么 😠

**Comment by fudiwei** [comment]
Fix this on [release v2.2.2](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.TenpayV2/2.2.2).
