### ISSUE TITLE
[BUG] 部分方法的 XML 文档解析失败

### ISSUE THREAD

**Issue by gehongyan** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#85]
**背景**

根据 W3C 标准，在 XML 文档中，需要将以下五个特殊字符转义为预定义实体：

| 特殊字符 | 预定义实体 |
| --- | --- | 
| `"` | quot |
| `&` | amp |
| `'` | apos |
| `<` | lt |
| `>` | gt |

.NET API 采用 XML 文档注释，注释文本中的特殊字符需按标准进行转义，否则 IDE 可能无法正确解析文档内容生成智能提示。

---

**问题描述**

以 [ExecuteGetPayOrderAsync] 为例，当前代码版本的 XML 注释在 IDE 中的呈现效果如图：

* JetBrains Rider

![image](https://user-images.githubusercontent.com/21241496/227444986-6306493c-861d-4561-87b7-633365405b26.png)

* Visual Studio

![image](https://user-images.githubusercontent.com/21241496/227445138-39061179-9cdc-407d-b410-357a390f8985.png)

由于代码注释中的微信支付文档引用链接中出现了 `&` 字符，使得 XML 注释无法正常解析。

根据标准，将 `&` 替换为 `&amp;` 进行转义修正后，XML 注释在 IDE 中的呈现效果如图：

* JetBrains Rider

![image](https://user-images.githubusercontent.com/21241496/227446698-ce8bb2a3-f1d9-4b79-a62c-5111dcb5f4ab.png)

* Visual Studio

![image](https://user-images.githubusercontent.com/21241496/227446563-c0328d2a-7cab-4b9f-8cbb-078091d8b489.png)

---

**参考资料**

> [Extensible Markup Language (XML) 1.1 (Second Edition)](https://www.w3.org/TR/xml11/#sec-predefined-ent)
> [XML 文档注释 - 使用 /// 注释记录 API | Microsoft Learn](https://learn.microsoft.com/zh-cn/dotnet/csharp/language-reference/xmldoc/)

[ExecuteGetPayOrderAsync]: https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/d71e4cd84414a4db057175cb21fbe10bc2d546c9/src/SKIT.FlurlHttpClient.Wechat.TenpayV2/Extensions/WechatTenpayClientExecutePayExtensions.cs#L66-L100

**Comment by fudiwei** [comment]
感谢建议。

我们其实也发现了这个问题，但是经过权衡之后还是依然选择了没有转义。

因为转义之后，虽然语法上符合 XML 规范了，但打开的超链接地址就错了 😂

图里的这个例子可能不是很明显，因为 URL 后面那个查询参数 `index=1` 其实没啥用，即便错了也能正常访问。但我们可以颠倒一下查询参数的顺序，把 `chapter=9_1` 放到后面：

```
https://pay.weixin.qq.com/wiki/doc/api/app/app.php?index=1&chapter=9_1
```

这个链接在 IDE 里 Ctrl+鼠标左键打开的是对的。

但如果转义的话，变成了：

```
https://pay.weixin.qq.com/wiki/doc/api/app/app.php?index=1&amp;chapter=9_1
```

这个链接打开就是 404 的了。

所以我们权衡之后最后还是选择了保留原始 URL，以便能正常使用超链接，但确实牺牲了一部分文档注释的功能。因为我们觉得“提供一个正确的参考链接”要比“提供文档注释”相对而言更重要一些。

---

其实这里更好的处理方式是把像 `index=1` 这种没有用的查询参数删掉，尽可能只保留到剩下一个查询参数、甚至没有查询参数，这样就规避了 `&` 字符需要转义的问题。但并非所有链接都能如此操作，还是会有一些会带有 `&` 字符的。

如果你有其他思路或想法欢迎继续探讨。

**Comment by gehongyan** [comment]
感谢详细回复。

---

> 因为转义之后，虽然语法上符合 XML 规范了，但打开的超链接地址就错了 😂

该问题我也注意到了，但或许需要更多地考虑用户在引用 NuGet 包时的使用体验。

当前的问题是，由于 XML 语法错误，开发者无法通过鼠标悬停文档与反编译源码查看任何提示信息，只能通过浏览本项目源码查看 SDK 开发者想提供给业务开发者想要传达的信息。但业务开发者并不知道，看不到任何信息是因为 XML 存在语法错误导致编译时 XML 信息被丢弃，还是 SDK 开发者并没有在 XML 文档中写下这些信息。

---

本回复包含两节：

* 当前现象与转义后的呈现效果
* 通过 CDATA 标签解决问题

---

## 当前现象与转义后的呈现效果

以此行 XML 文档为例：
https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/f6cda1a4ec7b761e0dd07c23349d634cbc7e13b0/src/SKIT.FlurlHttpClient.Wechat.TenpayV2/Extensions/WechatTenpayClientExecuteMerchantCustomsExtensions.cs#L51

#### 本项目源码中快捷打开 XML 文档中的链接

尝试通过住 Ctrl 键并单击的方式打开 XML 文档中的链接，从先前的截图中可以发现：

* Visual Studio

XML 文档中转义后的链接识别不正常，链接的识别截至到了分号 `;` 前。因此，通过此处点击打开的链接为：

转义后：
> **<https://pay.weixin.qq.com/wiki/doc/api/external/declarecustom.php?chapter=18_4&amp>**;index=3

* Rider 

虽然 XML 文档中转义后的链接识别完整，但打开的链接地址仍然为：

转义后：
> **<https://pay.weixin.qq.com/wiki/doc/api/external/declarecustom.php?chapter=18_4&amp;amp;index=3>**

在 IDE 中的 XML 文档源码处通过住 Ctrl 键并单击的方式打开链接，IDE 对于存在 XML 转义的链接的支持性不佳。

#### 用户引用本项目 NuGet 包通过鼠标悬停查看 API 文档

尝试通过鼠标悬停查看 API 文档：

* Visual Studio

转义前：
![image](https://user-images.githubusercontent.com/21241496/229271948-337559a9-557b-457d-b20b-fae5fc9ea799.png)

转义后：
![image](https://user-images.githubusercontent.com/21241496/229272927-5a055ee6-f6fc-4900-add1-832646eb694e.png)

* Rider

转义前：
![image](https://user-images.githubusercontent.com/21241496/229271976-1e2bb7ed-4480-4f5c-960e-de1e1200fcec.png)

转义后：
![image](https://user-images.githubusercontent.com/21241496/229272949-ad954f37-bb47-4392-8173-9f9550fb41b9.png)

转义前均未显示预期之内的 XML 文档，而转义后均可以通过悬停显示文档。

其中，Visual Studio 不支持点击悬停文档中的内容打开链接，Rider 可以通过点击悬停文档中的内容打开正确的链接。

#### 用户引用本项目 NuGet 包通过反编译查看源码 XML 文档

* Visual Studio

未转义的 XML 文档无法正确显示。

转义前：
![image](https://user-images.githubusercontent.com/21241496/229272142-1af18c61-3211-45ba-a123-21cad779f3f8.png)

转义的 XML 文档在反编译后虽然可以正确显示，但仍存在前文提到过的链接不正确的问题。

转义后：
![image](https://user-images.githubusercontent.com/21241496/229273087-3799ae52-6560-4e8b-89af-6fc11def869f.png)

* Rider

未转义的 XML 文档无法正确显示。

转义前：
![image](https://user-images.githubusercontent.com/21241496/229272265-cf6704a1-0f01-469c-b2c3-be2efc220e64.png)

转义的 XML 文档在反编译后虽然可以正确显示，但仍存在前文提到过的链接不正确的问题。

转义后：
![image](https://user-images.githubusercontent.com/21241496/229273127-d062aa3b-8f98-41aa-9742-c2f6964ea544.png)

---

## 通过 CDATA 标签解决问题

如果需要同时考虑 XML 文档源码中快捷点击打开链接、与悬停文档正确显示两方面，可以尝试使用 `CDATA` 标签。将链接部分包装在 CDATA 标签内，可以在保证源码 XML 文档中可以正确打开链接的前提下，使 NuGet 包的用户都能通过悬停或反编译查看源码查看正确的 API 文档。

* Visual Studio 

源码：
![image](https://user-images.githubusercontent.com/21241496/229273434-7317eccf-4f5e-41df-97b1-3d3f661d6cc6.png)

悬停文档：
![image](https://user-images.githubusercontent.com/21241496/229273560-775a2e6e-2947-4329-acb7-8efd446c8918.png)

反编译源码：
![image](https://user-images.githubusercontent.com/21241496/229273535-7ac96153-2019-43fe-8434-ca966e248272.png)

* Rider

源码：
![image](https://user-images.githubusercontent.com/21241496/229273629-392a10c0-474e-40f4-9f6a-e25352a5aa6b.png)

悬停文档：
![image](https://user-images.githubusercontent.com/21241496/229273668-478673d0-cb8d-4f3f-b4ff-1f89a140f1b8.png)

反编译源码：
![image](https://user-images.githubusercontent.com/21241496/229273691-1bbe47d8-5256-45d3-9872-cf18ebeabb31.png)

---

如果赞同使用 CDATA 标签解决以上问题，我就去把 #86 更新一下。

**Comment by fudiwei** [comment]
看起来 CDATA 是个好主意 👍

**Comment by gehongyan** [comment]
> 看起来 CDATA 是个好主意 👍

如果使用 CDATA 标签的话，要把所有的引用中 `REF: ` 后面的链接部分都进行包装嘛？还是只包装包含特殊字符 `&` 的引用链接即可呢？

我会比较倾向于前者，变更会比较多，但可以保持格式统一。

**Comment by fudiwei** [comment]
经过评估我们也认为统一使用 CDATA 包裹会更好。但涉及到多个库（不只局限于 Wechat 这个项目）的大范围变更，牵扯比较广，而此变更又不适合单独为此发布一个全新的 NuGet 版本，我们决定留待下一个大版本（即 3.x）发布时集中处理。

这个 Issue 我会保留到下一个大版本发布前，有最新进展会在此同步。

再次感谢您提供的建议和思路。

**Comment by fudiwei** [comment]
v3.x 已将全部文档注释中的链接调整为使用 CDATA 标签包裹。
