### ISSUE TITLE
视频号小店接口获取售后单，请求数据格式异常bug问题的修复

### ISSUE THREAD

**Issue by zupu8** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#90]
![KGX%N (RLP`T$M86OB 5URO](https://user-images.githubusercontent.com/11517114/229035235-b8ac86cd-180d-40c8-98cb-14ce3d8e7b7a.png)
请求的数据类型错误，要将long的数据格式修改为string的数据格式即可；

原始的属性类型：
`public long AftersaleOrderId { get; set; }`
修改后的属性类型：
`public string AftersaleOrderId { get; set; } = string.Empty;`

修改完请求就正常了。

**Comment by fudiwei** [comment]
我先确认一下这个字段实际是否是一个 int64、只是是字符串形式的吗？

我没有实际调用过视频号相关的接口，但我看它基本是照搬了小程序小商店的那套字段，在小商店里售后单号是数值类型的。

**Comment by zupu8** [comment]
我测试过了，如果类型是int64就是long类型的话，会报data format error，修改成string类型的话就能正常请求了。

**Comment by fudiwei** [comment]
我的意思是是否实际是一个 int64.ToString()？没有其他字符构成吧？

**Comment by fudiwei** [comment]
Fix this on [release v2.26.1](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.Api/2.26.1).
