### ISSUE TITLE
TenpayV2版本下单错误，提示：没有识别提供给安全包的凭证

### ISSUE THREAD

**Issue by gudieaofei** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#93]
使用V2版下预下单时，提示：没有识别提供给安全包的凭证，已经确认是有读取证书的字节流，查看源码，在初始化HttpClientFactory时，是使用：
`X509Certificate x509 = (_certPassword == null) ? new X509Certificate2(_certBytes) : new X509Certificate2(_certBytes, _certPassword);
handler.ClientCertificates.Add(x509);`
查询资料发现应该是要加上设置：X509KeyStorageFlags.MachineKeySet，
`X509Certificate x509 = new X509Certificate2(_certBytes ，_certPassword, X509KeyStorageFlags.MachineKeySet); `
请问除了提高帐户权限之外，还有什么方法解决这个问题？

**Comment by gudieaofei** [comment]
目前自定义了一个HttpClientFactory，然后在实例化客户端时调用Configure覆盖FlurlHttpClientFactory，如果你有更好的方式，请麻烦告诉我一声，谢谢
`
/// <summary>
    /// 自定义HttpClientFactory
    /// </summary>
    public class HttpClientFactory : Flurl.Http.Configuration.DefaultHttpClientFactory
    {
        private readonly byte[]? _certBytes;
        private readonly string? _certPassword;

        public HttpClientFactory(byte[]? certBytes, string? certPassword)
        {
            _certBytes = certBytes;
            _certPassword = certPassword;
        }

        public override HttpMessageHandler CreateMessageHandler()
        {
            HttpClientHandler handler = new HttpClientHandler();
            handler.ServerCertificateCustomValidationCallback = (requestMessage, certificate, chain, sslPolicyErrors) => sslPolicyErrors == SslPolicyErrors.None;

            if (_certBytes != null)
            {
                X509Certificate x509 = new X509Certificate2(_certBytes, _certPassword, X509KeyStorageFlags.MachineKeySet);
                handler.ClientCertificates.Add(x509);
            }

            return handler;
        }
    }
`
`
var client = new WechatTenpayClient(options);
        client.Configure((settings) =>
        {
            settings.FlurlHttpClientFactory = new HttpClientFactory(
                options.MerchantCertificateBytes,
                options.MerchantCertificatePassword ?? options.MerchantId
            );
        });
        services.AddSingleton(client);
`

**Comment by fudiwei** [comment]
请问是在 Framework 项目 + Windows Server 环境下吗？

**Comment by gudieaofei** [comment]
@fudiwei Net6项目+WebApi+Windows Server IIS部署环境，通过VS直接调试是没问题的，IIS托管模式下会有权限不足的问题

**Comment by fudiwei** [comment]
理论上这种改法会带来一些其他问题，您尝试一下这样修改是否可行：

```csharp
X509Certificate x509 = new X509Certificate2(_certBytes, _certPassword, X509KeyStorageFlags.MachineKeySet);
// 改为
X509Certificate x509 = new X509Certificate2(_certBytes, _certPassword, X509KeyStorageFlags.Exportable | X509KeyStorageFlags.EphemeralKeySet);
```

因为我这里没有可供测试的 Windows Server 设备，麻烦您尝试一下告知我结果，我会再发布一个 patch。

**Comment by gudieaofei** [comment]
测试了，以下两种写法都报错
`
X509Certificate x509 = new X509Certificate2(_certBytes, _certPassword, X509KeyStorageFlags.Exportable | X509KeyStorageFlags.EphemeralKeySet);

X509Certificate x509 = new X509Certificate2(_certBytes, _certPassword, X509KeyStorageFlags.Exportable | X509KeyStorageFlags.EphemeralKeySet | X509KeyStorageFlags.MachineKeySet);
`

以下两种写法可以正常支付
`
X509Certificate x509 = new X509Certificate2(_certBytes, _certPassword, X509KeyStorageFlags.MachineKeySet);

X509Certificate x509 = new X509Certificate2(_certBytes, _certPassword, X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.Exportable);
`

**Comment by gudieaofei** [comment]
不过报错的内容不是“没有识别提供给安全包的凭证”，而是变成了“Call failed. 不正确的数据。: POST https://api.mch.weixin.qq.com/pay/unifiedorder”

**Comment by fudiwei** [comment]
Fix this on [release v2.3.1](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.TenpayV2/2.3.1).
