### ISSUE TITLE
工作台关键数据，只能跳转小程序，不能跳转网页

### ISSUE THREAD

**Issue by leoskey** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#94]
https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/blob/830d8bf9ec7fa7d2d71cdba790feaa5c250f9263/src/SKIT.FlurlHttpClient.Wechat.Work/Extensions/WechatWorkClientExecuteCgibinAgentExtensions.cs#L137

企业微信开发者中心解答
https://developer.work.weixin.qq.com/community/question/detail?content_id=16452592468434270282

如果在设置工作台模板时，添加了 pagepath 字段，后续设置 jump_url 字段，并将 pagepath 设置为 null 或空字符，是不生效的。

我尝试过官方的回答，去除 pagepath 字段，是有效的。

但 ExecuteCgibinAgentSetWorkbenchTemplateAsync 只能同时设定 jump_url 与 pagepath 字段。是否考虑新增以下方式或等待官方调整

1. 增加类似 ExecuteCgibinAgentSetWorkbenchTemplateWithJumpUrlAsync 方法
2. 增加参数 ignorePagePath 到 ExecuteCgibinAgentSetWorkbenchTemplateAsync
3. 等待企业微信官方调整

**Comment by fudiwei** [comment]
> 添加了 pagepath 字段，后续设置 jump_url 字段，并将 pagepath 设置为 null 或空字符，是不生效的。

没太理解这个问题。

**Comment by leoskey** [comment]
> > 添加了 pagepath 字段，后续设置 jump_url 字段，并将 pagepath 设置为 null 或空字符，是不生效的。
> 
> 没太理解这个问题。

ExecuteCgibinAgentSetWorkbenchTemplateAsync 包含两个字段：

- pagepath 用于跳转小程序
- jump_url 用于跳转网页

字段详细说明链接：https://developer.work.weixin.qq.com/document/path/94620#%E5%85%B3%E9%94%AE%E6%95%B0%E6%8D%AE%E5%9E%8B

第一次设定跳转小程序模板，此时在企业微信工作台点击应用会跳转关联小程序的页面 `pages/index/index`
```
{
    "items":[
        {
            "key":"待审批",
            "data":"2",
            "pagepath":"pages/index/index"
        }
}
```
第二次设定跳转网页模板，此时在企业微信工作台点击应用会错误的跳转关联小程序的页面 `pages/index/index`
```
{
    "items":[
        {
            "key":"待审批",
            "data":"2",
            "jump_url":"http://www.qq.com"
        }
}
```

**Comment by fudiwei** [comment]
所以正常的数据结构应该是什么样子的？

**Comment by leoskey** [comment]
正常结构如下

跳转网页
```
{
    "agentid":1000005,
    "userid":"test",
    "type":"keydata",
    "keydata":{
        "items":[
            {
                "key":"待审批",
                "data":"2",
                "jump_url":"http://www.qq.com"
            }
        ]
    }
}
```

跳转小程序：
```
{
    "agentid":1000005,
    "userid":"test",
    "type":"keydata",
    "keydata":{
        "items":[
            {
                "key":"待审批",
                "data":"2",
                "pagepath":"pages/index"
            }
        ]
    }
}
```

**Comment by fudiwei** [comment]
呃，还是没太明白，这个跟前面你发的数据结构有什么差异吗？

**Comment by leoskey** [comment]
抱歉，我表达不准确。

我希望在企业微信工作台点击应用的关键数据后跳转网页，但通过 sdk 的 ExecuteCgibinAgentSetWorkbenchTemplateAsync 方法无法实现我的需求。

**问题原因**
当希望用户点击应用跳转网页时，应该设定 jump_url 字段，同时不要传输 pagepath 字段给微信 api。
```
// 正确的参数
{
    "agentid":1000005,
    "userid":"test",
    "type":"keydata",
    "keydata":{
        "items":[
            {
                "key":"待审批",
                "data":"2",
                "jump_url":"http://www.qq.com"
            }
        ]
    }
}
```

而 ExecuteCgibinAgentSetWorkbenchTemplateAsync 实际发送的参数
```
// 错误的参数
{
    "agentid":1000005,
    "userid":"test",
    "type":"keydata",
    "keydata":{
        "items":[
            {
                "key":"待审批",
                "data":"2",
                "jump_url":"http://www.qq.com",
                "pagepath":null // <- 原因所在，不应当在请求中包含这个参数
            }
        ]
    }
}
```

**Comment by fudiwei** [comment]
这跟你所使用的 JSON 序列化器有关。

默认情况下是不会序列化器值为 `null` 的属性，除非你在 `client.Configure()` 中手动修改了序列化器配置项。

- 如果你在使用 Newtonsoft.Json，那么需要配置为 `NullValueHandling = NullValueHandling.Ignore`。
- 如果你在使用 System.Text.Json，那么需要配置为 `DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull`。
