### ISSUE TITLE
企业微信api的ExecuteGetMediaFileBufferAsync接口获取文件失败

### ISSUE THREAD

**Issue by duzijian** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#95]
简单描述

企业微信api的ExecuteGetMediaFileBufferAsync接口获取文件失败
调试发现：
在获取一次分片后进行释放时(FinanceDllWindowsPInvoker.FreeMediaData)应用程序直接退出

源代码

使用
SKIT.FlurlHttpClient.Wechat.Work.UnitTests
`TestCase_FinanceSdkTests.cs`中的ExecuteGetMediaFileAsync

异常

在获取一次分片后进行释放时(FinanceDllWindowsPInvoker.FreeMediaData)应用程序直接退出

发生问题的运行环境

使用的模块及版本：Windows11
使用的模块及版本：.NET 6
使用的模块及版本：SKIT.FlurlHttpClient.Wechat.Work 2.16.0

**Comment by fudiwei** [comment]
可能存在 Double Free。

麻烦确认一下 `ExecuteGetChatRecordsAsync` 接口、即内部调用了 `FinanceDllWindowsPInvoker.FreeSlice` 的，有没有同样的闪退问题？

**Comment by duzijian** [comment]
首先 非常感谢您的回复

我调用了下`ExecuteGetChatRecordsAsync` 和 `ExecuteDecryptChatRecordAsync` 在FinanceDllWindowsPInvoker.FreeSlice的时候没有发现闪退现象；之后我再次调用`ExecuteGetMediaFileAsync`后，在`FinanceDllWindowsPInvoker.FreeMediaData` 还是出现了闪退
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/39946057/eeadff38-966f-4ae4-bc54-23160ecf4ae1)

**Comment by fudiwei** [comment]
我推送了一个新的分支 [bugfix/double_free](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/tree/bugfix/double_free)，尝试修复了该 Bug。

麻烦确认一下问题是否已解决，如果解决的话我再发版。谢谢🙏

**Comment by duzijian** [comment]
我刚刚尝试了一下 问题依然存在，还是同样在FinanceDllWindowsPInvoker.FreeMediaData出现闪退
似乎不是Double Free的问题，我查看了下企业微信的社区有同样的问题，链接如下：
https://developers.weixin.qq.com/community/develop/doc/0008caf08d82e81633ac894f651400?highLine=%25E4%25BC%2581%25E4%25B8%259A%25E5%25BE%25AE%25E4%25BF%25A1%25E5%2588%2586%25E7%2589%2587%25E6%258B%2589%25E5%258F%2596%25E5%25A4%259A%25E5%25AA%2592%25E4%25BD%2593%25E6%2595%25B0%25E6%258D%25AE%25E5%259C%25A8FreeMediaData%25E6%2597%25B6%25E9%2597%25AA%25E9%2580%2580

C#调用WeWorkFinanceSdk.dll 里面的FreeMediaData，报错
目前没有人回复是否解决

**Comment by duzijian** [comment]
目前释放的时候出现了这个异常
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/39946057/e5cfb648-3892-4319-87ab-4afe630ab635)

**Comment by duzijian** [comment]
大佬
我刚调试了下 注释图中的那行代码就可以正常运行了
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/39946057/6a958ead-5e40-4681-9d41-7fdb423ca281)

**Comment by fudiwei** [comment]
我们这面做个测试后验证下 Linux 环境后发版。

**Comment by duzijian** [comment]
好的
非常感谢

**Comment by fudiwei** [comment]
Fix this on [release v2.17.1](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.Work/2.17.1).
