### ISSUE TITLE
获取平台证书解密失败：mac check in GCM failed

### ISSUE THREAD

**Issue by Qintai** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#97]
使用的 源码项目中的   SKIT.FlurlHttpClient.Wechat.TenpayV3.Sample_Net6
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/55422114/17e791c4-122d-473a-86c6-67cf61795ee7)
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/55422114/825aa7fe-07a5-44e2-b661-7c4f3ea06cb7)

报错：mac check in GCM failed
ex.Source：SKIT.FlurlHttpClient.Wechat.TenpayV3
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/55422114/226cd255-93c3-4050-b66b-6ee382b9ab96)
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/assets/55422114/b589b69b-e1ee-407f-b9e2-b77c8e36d917)

**Comment by fudiwei** [comment]
检查传入的 API v3 密钥。

**Comment by Qintai** [comment]
后面我把 API v3 密钥换成Api 密钥就都可以了（SecretV3 写的api密钥），Jsapi下单、回调解密、刷新平台证书都通了。应该是我把 Api 密钥 和 API v3 密钥弄反了。
