### ISSUE TITLE
SKIT.FlurlHttpClient.Wechat.Api.WechatApiClientExecuteCgibinExtensions缺少接口

### ISSUE THREAD

**Issue by gudieaofei** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat#98]
https://developers.weixin.qq.com/doc/offiaccount/Basic_Information/getStableAccessToken.html

缺少接口：POST https://api.weixin.qq.com/cgi-bin/stable_token

**Comment by fudiwei** [comment]
欢迎 PR

**Comment by gudieaofei** [comment]
PR已推送
[Stable Access token](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.Wechat/pull/99)

**Comment by fudiwei** [comment]
Support this on [release v2.29.0](https://www.nuget.org/packages/SKIT.FlurlHttpClient.Wechat.Api/2.29.0).
